#ifndef TCTI_SCALAR_RUNTIME_SEMANTIC_SCENARIOS_H
#define TCTI_SCALAR_RUNTIME_SEMANTIC_SCENARIOS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

uint64_t tcti_semantic_case_add_extended_uxtw_uses_32bit_operand(void);
uint64_t tcti_semantic_case_add_shifted_hot_uses_scratch_carrier(void);
uint64_t tcti_semantic_case_asr_alias_sign_extends_extracted_field(void);
uint64_t tcti_semantic_case_dc_zva_zeroes_cache_block(void);
uint64_t tcti_semantic_case_dynamic_tag_scaled_store_uses_full_index(void);
uint64_t tcti_semantic_case_ldrh_cmp_ccmp_eq_survives_single_insn_blocks(void);
uint64_t tcti_semantic_case_logical_imm_memory_backed_source_uses_distinct_scratch(void);
uint64_t tcti_semantic_case_lsr_alias_uses_top_mask_not_rotate(void);
uint64_t tcti_semantic_case_musl_callback_slot_adrp_add_materializes_ldso_target_page(void);
uint64_t tcti_semantic_case_musl_calloc_overflow_guard_umulh_stays_zero_for_small_product(void);
uint64_t tcti_semantic_case_musl_calloc_plt_adrp_resolves_local_got_page(void);
uint64_t tcti_semantic_case_musl_dls3_dependency_chain_appends_next_dso(void);
uint64_t tcti_semantic_case_musl_find_sym_accepts_global_func(void);
uint64_t tcti_semantic_case_musl_find_sym_deps_post_index_walk_reads_first_dep(void);
uint64_t tcti_semantic_case_musl_find_sym_dls2b_from_ldso(void);
uint64_t tcti_semantic_case_musl_find_sym_longjmp_from_ldso(void);
uint64_t tcti_semantic_case_musl_find_sym_siglongjmp_from_ldso(void);
uint64_t tcti_semantic_case_musl_gnu_hash_malloc(void);
uint64_t tcti_semantic_case_musl_gnu_lookup_dls2b_chain(void);
uint64_t tcti_semantic_case_musl_gnu_lookup_filtered_malloc(void);
uint64_t tcti_semantic_case_musl_libc_name_compare_prefix_stays_on_match_path(void);
uint64_t tcti_semantic_case_musl_libc_name_literal_base_materializes_before_compare(void);
uint64_t tcti_semantic_case_musl_libc_name_setup_preserves_hot_x0_across_mov_x17_x25(void);
uint64_t tcti_semantic_case_musl_load_library_detects_libc_self(void);
uint64_t tcti_semantic_case_musl_malloc_sizeclass_rbit_clz(void);
uint64_t tcti_semantic_case_musl_mutex_ldaxr_stlxr_roundtrip(void);
uint64_t tcti_semantic_case_musl_opendir_calloc_nonnull_skips_close_path(void);
uint64_t tcti_semantic_case_musl_opened_libc_validation_uses_mul_alias(void);
uint64_t tcti_semantic_case_musl_relr_loop_terminates_at_table_end(void);
uint64_t tcti_semantic_case_musl_secs_to_tm_smulh_asr_sub_block(void);
uint64_t tcti_semantic_case_musl_snprintf_file_wpos_init(void);
uint64_t tcti_semantic_case_musl_strncmp_libc_reserved_prefix(void);
uint64_t tcti_semantic_case_musl_ubfiz_symbol_index_preserves_shifted_bits(void);
uint64_t tcti_semantic_case_musl_vdprintf_stack_file_zero_init(void);
uint64_t tcti_semantic_case_pltrel_rela_stride_selector(void);
uint64_t tcti_semantic_case_relocation_fault_path_uses_loaded_x5(void);
uint64_t tcti_semantic_case_relocation_loop_preserves_loaded_x5(void);
uint64_t tcti_semantic_case_smaddl_uses_signed_32bit_inputs(void);
uint64_t tcti_semantic_case_tst_x1_imm_sets_zero_flag(void);

#ifdef __cplusplus
}
#endif

#endif
