#ifndef TCTI_HARNESS_TRUTH_H
#define TCTI_HARNESS_TRUTH_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum {
    TCTI_HARNESS_INPUT_REGS = 16,
    TCTI_HARNESS_SNAPSHOT_REGS = 20,
};

typedef struct tcti_harness_snapshot {
    uint64_t in_regs[TCTI_HARNESS_INPUT_REGS];
    uint64_t out_regs[TCTI_HARNESS_SNAPSHOT_REGS];
} tcti_harness_snapshot_t;

void tcti_harness_seed_inputs(uint64_t regs[TCTI_HARNESS_INPUT_REGS]);
void tcti_harness_run_snapshot(void (*gadget)(void),
                               const uint64_t in_regs[TCTI_HARNESS_INPUT_REGS],
                               uint64_t out_regs[TCTI_HARNESS_SNAPSHOT_REGS]);

int tcti_harness_case_add_7_13_14(tcti_harness_snapshot_t *snapshot);
int tcti_harness_case_add_0_1_2(tcti_harness_snapshot_t *snapshot);
int tcti_harness_case_mov_2_7(tcti_harness_snapshot_t *snapshot);
uint64_t tcti_harness_case_entry_restores_pstate_for_bcond_ne(void);
uint64_t tcti_harness_case_cmp_w20_ccmp_gt_bls_uses_32bit_flags(void);
uint64_t tcti_harness_case_tpidr_el0_roundtrips_through_full_sysreg_encoding(void);
uint64_t tcti_harness_case_cmp_w2_w1_uxtb_csel_uses_w_width(void);
uint64_t tcti_harness_case_csel_eq_selects_true_operand(void);
uint64_t tcti_harness_case_csel_preserves_flags_for_bcond(void);
uint64_t tcti_harness_case_cmp_csel_ls_hs_tracks_unsigned_minmax(void);
uint64_t tcti_harness_case_cmp_csinv_ls_preserves_nonoverflow_size(void);
uint64_t tcti_harness_case_cmp_csinv_ls_saturates_overflow_size(void);
uint64_t tcti_harness_case_generated_cinc_ne_increments_only_on_ne(void);
uint64_t tcti_harness_case_vsnprintf_zero_size_cset_ne_preserves_zero_flag(void);
uint64_t tcti_harness_case_generated_vsnprintf_zero_size_length(void);
uint64_t tcti_harness_case_cmp_add_csel_ne_uses_preserved_zero_flag(void);
uint64_t tcti_harness_case_cmp_ccmp_false_immediate_clears_zero(void);
uint64_t tcti_harness_case_strchrnul_vector_mask_finds_dot(void);
uint64_t tcti_harness_case_strchrnul_byte_loop_stops_on_match_or_nul(void);
uint64_t tcti_harness_case_logical_mov_roundtrips_memory_backed_x19(void);
uint64_t tcti_harness_case_cset_eq_then_add_to_x3(void);
uint64_t tcti_harness_case_ldr_x5_from_memory_backed_x27(void);
uint64_t tcti_harness_case_str_x0_to_memory_backed_x22_scaled_x1(void);
uint64_t tcti_harness_case_add_hot_pair_to_memory_backed_x23(void);
uint64_t tcti_harness_case_cmp_memory_backed_x27_x23_branches_eq(void);
uint64_t tcti_harness_case_stack_pair_roundtrips_hot_x5_x4(void);
uint64_t tcti_harness_case_ldp_first_destination_preserves_pair_base(void);
uint64_t tcti_harness_case_ldp_post_index_first_destination_preserves_pair_base(void);
uint64_t tcti_harness_case_dynamic_tag_scaled_store_uses_full_index(void);
uint64_t tcti_harness_case_musl_ubfiz_symbol_index_preserves_shifted_bits(void);
uint64_t tcti_harness_case_lsr_alias_uses_top_mask_not_rotate(void);
uint64_t tcti_harness_case_musl_relr_loop_terminates_at_table_end(void);
uint64_t tcti_harness_case_pltrel_rela_stride_selector(void);
uint64_t tcti_harness_case_relocation_loop_preserves_loaded_x5(void);
uint64_t tcti_harness_case_relocation_fault_path_uses_loaded_x5(void);
uint64_t tcti_harness_case_musl_vdprintf_stack_file_zero_init(void);
uint64_t tcti_harness_case_dc_zva_zeroes_cache_block(void);
uint64_t tcti_harness_case_musl_snprintf_file_wpos_init(void);
uint64_t tcti_harness_case_musl_strncmp_libc_reserved_prefix(void);
uint64_t tcti_harness_case_musl_load_library_detects_libc_self(void);
uint64_t tcti_harness_case_musl_dls3_dependency_chain_appends_next_dso(void);
uint64_t tcti_harness_case_musl_find_sym_deps_post_index_walk_reads_first_dep(void);
uint64_t tcti_harness_case_musl_opened_libc_validation_uses_mul_alias(void);
uint64_t tcti_harness_case_musl_gnu_hash_malloc(void);
uint64_t tcti_harness_case_musl_calloc_plt_adrp_resolves_local_got_page(void);
uint64_t tcti_harness_case_musl_gnu_lookup_filtered_malloc(void);
uint64_t tcti_harness_case_musl_gnu_lookup_dls2b_chain(void);
uint64_t tcti_harness_case_musl_find_sym_dls2b_from_ldso(void);
uint64_t tcti_harness_case_musl_find_sym_longjmp_from_ldso(void);
uint64_t tcti_harness_case_musl_find_sym_siglongjmp_from_ldso(void);
uint64_t tcti_harness_case_musl_find_sym_accepts_global_func(void);
uint64_t tcti_harness_case_add_shifted_hot_uses_scratch_carrier(void);
uint64_t tcti_harness_case_add_extended_uxtw_uses_32bit_operand(void);
uint64_t tcti_harness_case_logical_imm_memory_backed_source_uses_distinct_scratch(void);
uint64_t tcti_harness_case_musl_malloc_sizeclass_rbit_clz(void);
uint64_t tcti_harness_case_musl_opendir_calloc_nonnull_skips_close_path(void);
uint64_t tcti_harness_case_musl_calloc_overflow_guard_umulh_stays_zero_for_small_product(void);
uint64_t tcti_harness_case_musl_callback_slot_adrp_add_materializes_ldso_target_page(void);
uint64_t tcti_harness_case_musl_libc_name_setup_preserves_hot_x0_across_mov_x17_x25(void);
uint64_t tcti_harness_case_musl_libc_name_literal_base_materializes_before_compare(void);
uint64_t tcti_harness_case_musl_libc_name_compare_prefix_stays_on_match_path(void);
uint64_t tcti_harness_case_musl_mutex_ldaxr_stlxr_roundtrip(void);
uint64_t tcti_harness_case_tst_x1_imm_sets_zero_flag(void);
uint64_t tcti_harness_case_ldrh_cmp_ccmp_eq_survives_single_insn_blocks(void);
uint64_t tcti_harness_case_musl_ls_root_post_open_callback_scan(void);
uint64_t tcti_harness_case_ldp_x2_x0_from_memory_backed_x21(void);
uint64_t tcti_harness_case_ldr_x2_imm0_from_memory_backed_x21(void);
uint64_t tcti_harness_case_ldr_x1_imm_from_memory_backed_x21(void);
uint64_t tcti_harness_case_ldr_x0_imm8_from_memory_backed_x21(void);
uint64_t tcti_harness_case_manual_two_ldr_shared_block_from_memory_backed_x21(void);
uint64_t tcti_harness_case_manual_two_ldr_shared_block_with_pc_advance(void);
uint64_t tcti_harness_case_generated_ldp_x2_x0_bytecode_matches_manual_shape(void);
uint64_t tcti_harness_case_reg_offset_ldr_x0_alias_base_reads_expected_qword(void);
uint64_t tcti_harness_case_generated_reg_offset_ldr_x0_alias_base_reads_expected_qword(void);
uint64_t tcti_harness_case_musl_callback_table_walk_materializes_dispatch_args(void);
uint64_t tcti_harness_case_musl_callback_prefix_materializes_args(void);
uint64_t tcti_harness_case_musl_callback_slot_loads_branch_target(void);
uint64_t tcti_harness_case_smaddl_uses_signed_32bit_inputs(void);
uint64_t tcti_harness_case_musl_frame_stride_block_uses_wide_immediates_and_reg_offset_ldr(void);
uint64_t tcti_harness_case_reg_offset_ldr_w_helper_reads_hot_x0_offset(void);
uint64_t tcti_harness_case_generated_ldr_w_reg_offset_reads_hot_x0_offset(void);
uint64_t tcti_harness_case_musl_frame_stride_prefix_then_ldr_in_next_block(void);
uint64_t tcti_harness_case_movz_smull_prefix_preserves_expected_x0(void);
uint64_t tcti_harness_case_umaddl_uses_unsigned_32bit_inputs(void);
uint64_t tcti_harness_case_lslv_64bit_uses_full_shift_amount(void);
uint64_t tcti_harness_case_lslv_memory_backed_registers_roundtrip(void);
uint64_t tcti_harness_case_sp_relative_ldr_str_roundtrip(void);
uint64_t tcti_harness_case_qsort_pointer_slot_updates_roundtrip(void);
uint64_t tcti_harness_case_busybox_scandir_flatten_block_roundtrip(void);
uint64_t tcti_harness_case_busybox_input_widechar_copy_loop_roundtrip(void);
uint64_t tcti_harness_case_musl_qsort_tbz_w0_signbit_branch(void);
uint64_t tcti_harness_case_musl_qsort_tbnz_w0_signbit_branches(void);
uint64_t tcti_harness_case_musl_qsort_csinc_tst_gate_keeps_expected_path(void);
uint64_t tcti_harness_case_logical_mov_memory_to_memory_roundtrip(void);
uint64_t tcti_harness_case_musl_qsort_rbit_clz_64bit_roundtrip(void);
uint64_t tcti_harness_case_musl_qsort_trailing_zero_block(void);
uint64_t tcti_harness_case_musl_qsort_extract_prefix_preserves_pshift_state(void);
uint64_t tcti_harness_case_musl_qsort_shift_merge_block_uses_live_hot_regs(void);
uint64_t tcti_harness_case_musl_qsort_restore_block_rebuilds_live_frame(void);
uint64_t tcti_harness_case_musl_qsort_reentry_block_preserves_head_and_pshift_inputs(void);
uint64_t tcti_harness_case_musl_memcpy8_tail_roundtrip(void);
uint64_t tcti_harness_case_musl_bucket_bitmask_block_roundtrip(void);
uint64_t tcti_harness_case_str_xzr_post_index_writes_back_base(void);
uint64_t tcti_harness_case_musl_ls_root_post_open_bucket_loop(void);
uint64_t tcti_harness_case_musl_ls_root_frame_list_walk(void);
uint64_t tcti_harness_case_busybox_ls_retry_ccmp_close_path(void);
uint64_t tcti_harness_case_busybox_allocator_msub_callback_roundtrip(void);
uint64_t tcti_harness_case_musl_pthread_mutex_lock_prefix(void);
uint64_t tcti_harness_case_musl_pthread_mutex_lock_fast_path(void);
uint64_t tcti_harness_case_musl_mutex_unlock_normal_type_branches_to_fast_unlock(void);
uint64_t tcti_harness_case_musl_memset_dup_zeroes_vector_store(void);
uint64_t tcti_harness_case_musl_memset_dup_replicates_byte_fill(void);
uint64_t tcti_harness_case_udiv_preserves_flags_for_csel_eq(void);

#ifdef __cplusplus
}
#endif

#endif
