#ifndef TCTI_MEMORY_ATOMIC_RUNTIME_SEMANTIC_SCENARIOS_H
#define TCTI_MEMORY_ATOMIC_RUNTIME_SEMANTIC_SCENARIOS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

uint64_t tcti_semantic_case_busybox_allocator_msub_callback_roundtrip(void);
uint64_t tcti_semantic_case_busybox_input_widechar_copy_loop_roundtrip(void);
uint64_t tcti_semantic_case_busybox_ls_retry_ccmp_close_path(void);
uint64_t tcti_semantic_case_busybox_scandir_flatten_block_roundtrip(void);
uint64_t tcti_semantic_case_generated_ldp_x2_x0_bytecode_matches_manual_shape(void);
uint64_t tcti_semantic_case_generated_ldr_w_reg_offset_reads_hot_x0_offset(void);
uint64_t tcti_semantic_case_generated_reg_offset_ldr_x0_alias_base_reads_expected_qword(void);
uint64_t tcti_semantic_case_ldp_x2_x0_from_memory_backed_x21(void);
uint64_t tcti_semantic_case_ldr_x0_imm8_from_memory_backed_x21(void);
uint64_t tcti_semantic_case_ldr_x1_imm_from_memory_backed_x21(void);
uint64_t tcti_semantic_case_ldr_x2_imm0_from_memory_backed_x21(void);
uint64_t tcti_semantic_case_logical_mov_memory_to_memory_roundtrip(void);
uint64_t tcti_semantic_case_lslv_64bit_uses_full_shift_amount(void);
uint64_t tcti_semantic_case_lslv_memory_backed_registers_roundtrip(void);
uint64_t tcti_semantic_case_manual_two_ldr_shared_block_from_memory_backed_x21(void);
uint64_t tcti_semantic_case_manual_two_ldr_shared_block_with_pc_advance(void);
uint64_t tcti_semantic_case_movz_smull_prefix_preserves_expected_x0(void);
uint64_t tcti_semantic_case_musl_bucket_bitmask_block_roundtrip(void);
uint64_t tcti_semantic_case_musl_callback_prefix_materializes_args(void);
uint64_t tcti_semantic_case_musl_callback_slot_loads_branch_target(void);
uint64_t tcti_semantic_case_musl_callback_table_walk_materializes_dispatch_args(void);
uint64_t tcti_semantic_case_musl_frame_stride_block_uses_wide_immediates_and_reg_offset_ldr(void);
uint64_t tcti_semantic_case_musl_frame_stride_prefix_then_ldr_in_next_block(void);
uint64_t tcti_semantic_case_musl_ls_long_vector_tail_and_dynamic_tag_scan(void);
uint64_t tcti_semantic_case_musl_ls_root_post_open_bucket_loop(void);
uint64_t tcti_semantic_case_musl_ls_root_post_open_callback_scan(void);
uint64_t tcti_semantic_case_musl_memcpy8_tail_roundtrip(void);
uint64_t tcti_semantic_case_musl_mutex_unlock_normal_type_branches_to_fast_unlock(void);
uint64_t tcti_semantic_case_musl_pthread_mutex_lock_fast_path(void);
uint64_t tcti_semantic_case_musl_pthread_mutex_lock_prefix(void);
uint64_t tcti_semantic_case_musl_qsort_csinc_tst_gate_keeps_expected_path(void);
uint64_t tcti_semantic_case_musl_qsort_extract_prefix_preserves_pshift_state(void);
uint64_t tcti_semantic_case_musl_qsort_rbit_clz_64bit_roundtrip(void);
uint64_t tcti_semantic_case_musl_qsort_reentry_block_preserves_head_and_pshift_inputs(void);
uint64_t tcti_semantic_case_musl_qsort_restore_block_rebuilds_live_frame(void);
uint64_t tcti_semantic_case_musl_qsort_shift_merge_block_uses_live_hot_regs(void);
uint64_t tcti_semantic_case_musl_qsort_tbnz_w0_signbit_branches(void);
uint64_t tcti_semantic_case_musl_qsort_tbz_w0_signbit_branch(void);
uint64_t tcti_semantic_case_musl_qsort_trailing_zero_block(void);
uint64_t tcti_semantic_case_qsort_pointer_slot_updates_roundtrip(void);
uint64_t tcti_semantic_case_reg_offset_ldr_w_helper_reads_hot_x0_offset(void);
uint64_t tcti_semantic_case_reg_offset_ldr_x0_alias_base_reads_expected_qword(void);
uint64_t tcti_semantic_case_sp_relative_ldr_str_roundtrip(void);
uint64_t tcti_semantic_case_str_xzr_post_index_writes_back_base(void);
uint64_t tcti_semantic_case_udiv_preserves_flags_for_csel_eq(void);
uint64_t tcti_semantic_case_umaddl_uses_unsigned_32bit_inputs(void);

#ifdef __cplusplus
}
#endif

#endif
