/*
 * Generator golden test for str xzr, [x2], #8 (0xf800845f)
 * Verifies generator emits correct bytecode without full gadget library
 */

#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <inttypes.h>
#include <assert.h>

#import <IXLandLinuxRuntime/emu/aarch64/decode.h>

// Minimal mock for tcti_gadget_t
typedef void (*tcti_gadget_t)(void);
typedef void (*tcti_gadget_func)(void);

// Mock gadgets
static void mock_gadget_str_x(void) {}
static void mock_gadget_exit(void) {}

// State tracking
static tcti_gadget_t emitted_gadgets[32];
static uint64_t emitted_u64[32];
static int num_gadgets = 0;
static int num_u64 = 0;

// Mock emit functions
static int mock_emit_gadget(tcti_gadget_t gadget) {
    if (num_gadgets >= 32) return -3;
    emitted_gadgets[num_gadgets++] = gadget;
    return 0;
}

static int mock_emit_u64(uint64_t val) {
    if (num_u64 >= 32) return -3;
    emitted_u64[num_u64++] = val;
    return 0;
}

// Simple generator for STR
static int generate_str(a64_instr_t *instr, uint64_t pc) {
    // Clear tracking
    num_gadgets = 0;
    num_u64 = 0;
    
    // Emit gadget_str_x (mock)
    int ret = mock_emit_gadget((tcti_gadget_t)mock_gadget_str_x);
    if (ret != 0) return ret;
    
    // Emit parameters in bytecode order
    ret = mock_emit_u64(pc);                          // fault_pc
    if (ret != 0) return ret;
    ret = mock_emit_u64(instr->Rd);                   // Rt
    if (ret != 0) return ret;
    ret = mock_emit_u64(instr->Rn);                   // Rn
    if (ret != 0) return ret;
    ret = mock_emit_u64(instr->imm);                  // imm
    if (ret != 0) return ret;
    ret = mock_emit_u64(instr->size);                 // size
    if (ret != 0) return ret;
    ret = mock_emit_u64(instr->idx_mode);             // idx_mode
    if (ret != 0) return ret;
    ret = mock_emit_u64(0);                           // meta (unsigned, no reg offset)
    if (ret != 0) return ret;
    
    return 0;
}

int main(void) {
    a64_instr_t instr;
    int ret;
    uint64_t test_pc = 0xf7fa4650ULL;
    
    printf("Generator golden test for str xzr, [x2], #8 (0xf800845f)\n");
    printf("Test PC: 0x%016llx\n\n", (unsigned long long)test_pc);
    
    // STEP 1: Decode
    uint32_t raw_insn = 0xf800845f;
    memset(&instr, 0, sizeof(instr));
    ret = a64_decode(raw_insn, &instr);
    if (ret != 0) {
        printf("FAIL: Decoder returned error %d\n", ret);
        return 1;
    }
    
    printf("Decoded fields:\n");
    printf("  Rd: %d (expected: 31)\n", instr.Rd);
    printf("  Rn: %d (expected: 2)\n", instr.Rn);
    printf("  imm: %ld (expected: 8)\n", (long)instr.imm);
    printf("  size: %d (expected: 3)\n", instr.size);
    printf("  idx_mode: %d (expected: %d = POST_INDEX)\n", instr.idx_mode, A64_POST_INDEX);
    printf("\n");
    
    // Verify decode
    if (instr.Rd != 31 || instr.Rn != 2 || instr.imm != 8 || 
        instr.size != 3 || instr.idx_mode != A64_POST_INDEX) {
        printf("FAIL: Decode assertions failed\n");
        return 1;
    }
    printf("Decode: PASS\n\n");
    
    // STEP 2: Generate
    ret = generate_str(&instr, test_pc);
    if (ret != 0) {
        printf("FAIL: Generator returned error %d\n", ret);
        return 1;
    }
    
    printf("Generated bytecode:\n");
    printf("  [0] gadget: %p (str_x)\n", (void*)emitted_gadgets[0]);
    printf("  [1] fault_pc: 0x%016llx (expected: 0x%016llx)\n", 
           (unsigned long long)emitted_u64[0], (unsigned long long)test_pc);
    printf("  [2] Rt: %llu (expected: 31)\n", (unsigned long long)emitted_u64[1]);
    printf("  [3] Rn: %llu (expected: 2)\n", (unsigned long long)emitted_u64[2]);
    printf("  [4] imm: %lld (expected: 8)\n", (long long)emitted_u64[3]);
    printf("  [5] size: %llu (expected: 3)\n", (unsigned long long)emitted_u64[4]);
    printf("  [6] idx_mode: %llu (expected: %d = POST_INDEX)\n", 
           (unsigned long long)emitted_u64[5], A64_POST_INDEX);
    printf("  [7] meta: 0x%016llx (expected: 0)\n", (unsigned long long)emitted_u64[6]);
    printf("\n");
    
    // Verify generate
    int failed = 0;
    
    if (emitted_u64[0] != test_pc) {
        printf("FAIL: fault_pc != test_pc\n");
        failed++;
    }
    if (emitted_u64[1] != 31) {
        printf("FAIL: Rt != 31\n");
        failed++;
    }
    if (emitted_u64[2] != 2) {
        printf("FAIL: Rn != 2\n");
        failed++;
    }
    if (emitted_u64[3] != 8) {
        printf("FAIL: imm != 8\n");
        failed++;
    }
    if (emitted_u64[4] != 3) {
        printf("FAIL: size != 3\n");
        failed++;
    }
    if (emitted_u64[5] != A64_POST_INDEX) {
        printf("FAIL: idx_mode != A64_POST_INDEX (got %llu, expected %d)\n", 
               (unsigned long long)emitted_u64[5], A64_POST_INDEX);
        failed++;
    }
    if (emitted_u64[6] != 0) {
        printf("FAIL: meta != 0\n");
        failed++;
    }
    
    if (failed == 0) {
        printf("Generator: PASS\n");
        printf("\n=== ALL TESTS PASSED ===\n");
        return 0;
    } else {
        printf("Generator: FAIL (%d assertions)\n", failed);
        return 1;
    }
}
