#import <XCTest/XCTest.h>

#include "../../Support/ISAFamilies/Memory/tcti_memory_atomic_runtime_semantic_scenarios.h"
#include "../../Support/ISAFamilies/Memory/tcti_memory_pair_semantic_scenarios.h"

@interface TCTIPairAndFrameSemanticTests : XCTestCase
@end

@implementation TCTIPairAndFrameSemanticTests

- (void)testSemanticExecutionContract_QsortPointerSlotUpdatesRoundtrip
{
    XCTAssertEqual(tcti_semantic_case_qsort_pointer_slot_updates_roundtrip(), 0ULL,
                   @"TCTI must preserve musl qsort's pointer-slot register-offset store, pair "
                    "load, and post-index writeback semantics for 8-byte element shuffles.");
}

- (void)testSemanticExecutionContract_MuslQsortRestoreBlockRebuildsLiveFrame
{
    XCTAssertEqual(tcti_semantic_case_musl_qsort_restore_block_rebuilds_live_frame(), 0ULL,
                   @"TCTI must restore musl qsort's spilled frame through the live LDP/MOV "
                    "epilogue block, because that block reconstructs the comparator head, step "
                    "state, and pshift inputs before re-entering the smoothsort loop.");
}

- (void)testSemanticExecutionContract_MuslQsortReentryBlockPreservesHeadAndPshiftInputs
{
    XCTAssertEqual(tcti_semantic_case_musl_qsort_reentry_block_preserves_head_and_pshift_inputs(),
                   0ULL,
                   @"TCTI must preserve musl qsort's re-entry frame build, because the live "
                    "block saves the current head on the stack, zero-extends w4 into pshift, and "
                    "materializes the next smoothsort iteration inputs before branching.");
}

- (void)testSemanticExecutionContract_LDPX2X0FromMemoryBackedX21
{
    XCTAssertEqual(tcti_semantic_case_ldp_x2_x0_from_memory_backed_x21(), 0ULL,
                   @"TCTI must preserve both 64-bit destinations for LDP X2,X0,[X21] when the "
                    @"base register is memory-backed and the pair feeds the live musl callback "
                     "argument path");
}

- (void)testSemanticExecutionContract_GeneratedLDPX2X0BytecodeMatchesManualShape
{
    XCTAssertEqual(
        tcti_semantic_case_generated_ldp_x2_x0_bytecode_matches_manual_shape(), 0ULL,
        @"The generated bytecode for LDP X2,X0,[X21] must match the working manual two-load "
         @"stream: two LDR helper gadgets, one pc-advance, and one exit with the expected "
         @"parameter order and offsets");
}

- (void)testSemanticExecutionContract_StackPairRoundtripsHotX5X4
{
    XCTAssertEqual(tcti_semantic_case_stack_pair_roundtrips_hot_x5_x4(), 0ULL,
                   @"TCTI STP/LDP on the guest stack must preserve hot registers x5 and x4 "
                    "across the dynamic linker symbol lookup path");
}

- (void)testSemanticExecutionContract_StackPairStoresMemoryBackedX20X21
{
    XCTAssertEqual(tcti_semantic_case_stack_pair_stores_memory_backed_x20_x21(), 0ULL,
                   @"TCTI STP from memory-backed x20/x21 to the guest stack must store both "
                    "values, preserve SP for offset mode, and advance PC past the prologue pair "
                    "store used in the busybox prompt path");
}

- (void)testSemanticExecutionContract_BusyboxStackCanaryEqualPathBranchesToRestore
{
    XCTAssertEqual(tcti_semantic_case_busybox_stack_canary_equal_path_branches_to_restore(), 0ULL,
                   @"TCTI must preserve the busybox stack-canary equal path through indirect "
                    "canary load plus SUBS/B.EQ so the compare branches to the restore block");
}

- (void)testSemanticExecutionContract_BusyboxStackRestoreBlockRestoresFrame
{
    XCTAssertEqual(tcti_semantic_case_busybox_stack_restore_block_restores_frame(), 0ULL,
                   @"TCTI must preserve the busybox restore block: memory-backed LDP pairs, "
                    "frame unwind, and RET after the canary compare succeeds");
}

- (void)testSemanticExecutionContract_BusyboxStackCanaryMismatchCallsFailPath
{
    XCTAssertEqual(tcti_semantic_case_busybox_stack_canary_mismatch_calls_fail_path(), 0ULL,
                   @"TCTI must take the busybox stack-canary mismatch path to the fail call "
                    "site when the saved stack slot differs from the live canary value");
}

- (void)testSemanticExecutionContract_LDPFirstDestinationPreservesPairBase
{
    XCTAssertEqual(tcti_semantic_case_ldp_first_destination_preserves_pair_base(), 0ULL,
                   @"TCTI LDP must compute both pair addresses from the original base even when "
                    "the first destination register is also the base register");
}

- (void)testSemanticExecutionContract_LDPPostIndexHotFirstDestinationPreservesPairBase
{
    XCTAssertEqual(tcti_semantic_case_ldp_post_index_hot_first_destination_preserves_pair_base(),
                   0ULL,
                   @"TCTI LDP post-index must write back from the original hot base register even "
                    "when the first destination register aliases that base.");
}

- (void)testSemanticExecutionContract_LDPPostIndexFirstDestinationPreservesPairBase
{
    XCTAssertEqual(tcti_semantic_case_ldp_post_index_first_destination_preserves_pair_base(), 0ULL,
                   @"TCTI LDP post-index must still compute both pair loads from the original "
                    "base even when the first destination register aliases that base.");
}

- (void)testSemanticExecutionContract_LDPSWPairSignExtendsLiveMuslOffsets
{
    XCTAssertEqual(tcti_semantic_case_ldpsw_pair_sign_extends_live_musl_offsets(), 0ULL,
                   @"TCTI LDPSW must sign-extend both 32-bit pair elements before musl adds "
                    "stack offsets into the live group/passwd result buffer.");
}

- (void)testSemanticExecutionContract_MuslGetgrgidMatchPathPublishesResultSlot
{
    XCTAssertEqual(tcti_semantic_case_musl_getgrgid_match_path_publishes_result_slot(), 0ULL,
                   @"TCTI must preserve musl's live getgrgid match path so the helper publishes "
                    "a real struct group pointer into the result slot instead of stale stack data.");
}

- (void)testSemanticExecutionContract_MuslGetgrgidReallocTailPublishesBufferBase
{
    XCTAssertEqual(tcti_semantic_case_musl_getgrgid_realloc_tail_publishes_buffer_base(), 0ULL,
                   @"TCTI must preserve musl's post-realloc getgrgid tail so the shared buffer "
                    "base and size slots stay valid before the match path builds gr_name.");
}

@end
