/*
 * TCTI Gadget Table Declarations
 * Auto-generated by tcti-gadget-gen.py
 * Version: 1.0.0
 * Date: 2026-03-20 22:31:24
 *
 * DO NOT EDIT - This file is machine generated
 */

#ifndef AARCH64_TCTI_GADGETS_H
#define AARCH64_TCTI_GADGETS_H

#include "misc.h"

#ifdef __cplusplus
extern "C" {
#endif

// Gadget function type
typedef void (*tcti_gadget_t)(void);

// Maximum gadgets per basic block
#define A64_MAX_GADGETS_PER_BLOCK 256

// Standard gadget epilogue - load next gadget and branch
// x28 = gadget stream pointer (increments by 8 each gadget)
// x27 = temp register, holds next gadget address
// x29 = cpu_state pointer
#define GADGET_EPILOGUE \
    "ldr x27, [x28], #8\n\t" \
    "br x27\n\t"

// Exit reason codes
#define TCTI_EXIT_NORMAL    0
#define TCTI_EXIT_SYSCALL   1
#define TCTI_EXIT_SIGNAL    2
#define TCTI_EXIT_FAULT     3

// Block exit function
extern void tcti_exit_block(int reason);

// ============================================================================
// Data Processing - Register Gadgets
// ============================================================================

// ADD Rd, Rn, Rm - 16x16x16 = 4096 gadgets
extern const tcti_gadget_t gadget_add_reg[16][16][16];

// SUB Rd, Rn, Rm - 16x16x16 = 4096 gadgets
extern const tcti_gadget_t gadget_sub_reg[16][16][16];

// AND Rd, Rn, Rm - 16x16x16 = 4096 gadgets
extern const tcti_gadget_t gadget_and_reg[16][16][16];

// ORR Rd, Rn, Rm - 16x16x16 = 4096 gadgets
extern const tcti_gadget_t gadget_orr_reg[16][16][16];

// EOR Rd, Rn, Rm - 16x16x16 = 4096 gadgets
extern const tcti_gadget_t gadget_eor_reg[16][16][16];

// MOV Rd, Rn - 16x16 = 256 gadgets
extern const tcti_gadget_t gadget_mov_reg[16][16];

// ============================================================================
// Data Processing - Immediate Gadgets
// ============================================================================

// ADD Rd, Rn, #imm (simplified: small immediates 0-15)
extern const tcti_gadget_t gadget_add_imm[16][16];

// SUB Rd, Rn, #imm (simplified: small immediates 0-15)
extern const tcti_gadget_t gadget_sub_imm[16][16];

// MOVZ Rd, #imm (simplified: 0-15)
extern const tcti_gadget_t gadget_mov_imm[16];

// ============================================================================
// Branch Gadgets
// ============================================================================

// Unconditional branch
extern tcti_gadget_t gadget_b;

// Conditional branch (tests condition flags)
extern tcti_gadget_t gadget_bcond;

// Compare and branch on zero
extern tcti_gadget_t gadget_cbz;

// Compare and branch on non-zero
extern tcti_gadget_t gadget_cbnz;

// Branch to register (ret, br, blr)
extern tcti_gadget_t gadget_br;

// ============================================================================
// System Gadgets
// ============================================================================

// System call
extern tcti_gadget_t gadget_svc;

// MRS (system register read)
extern tcti_gadget_t gadget_mrs;

// MSR (system register write)
extern tcti_gadget_t gadget_msr;

// NOP
extern tcti_gadget_t gadget_nop;

#ifdef __cplusplus
}
#endif

#endif /* AARCH64_TCTI_GADGETS_H */
