/*
 * TCTI Gadget Table Declarations
 * Auto-generated by tcti-gadget-gen.py
 * Version: 1.0.0
 * Date: 2026-03-26 02:56:10
 * Generator Hash: b8310813dcf4cc2a
 *
 * DO NOT EDIT - This file is machine generated
 * Source of truth: tcti/aarch64/tcti-gadget-gen.py
 * Regenerate with: python3 tcti/aarch64/tcti-gadget-gen.py -o <output_dir>
 */

#ifndef AARCH64_TCTI_GADGETS_H
#define AARCH64_TCTI_GADGETS_H

#include "misc.h"

#ifdef __cplusplus
extern "C" {
#endif

struct cpu_state;

// Gadget function type
typedef void (*tcti_gadget_t)(void);

// Maximum gadgets per basic block
#define A64_MAX_GADGETS_PER_BLOCK 512

// Exit reason codes
#define TCTI_EXIT_NORMAL    0
#define TCTI_EXIT_SYSCALL   1
#define TCTI_EXIT_SIGNAL    2
#define TCTI_EXIT_FAULT     3
#define TCTI_EXIT_COMPLEX   4  // Complex instruction needs C handling (e.g., load/store)

// Block exit function
extern void tcti_exit_block(int reason);

// Standard gadget epilogue - load next gadget and branch
#define GADGET_EPILOGUE "ldr x27, [x28], #8\n\tbr x27\n\t"

// ============================================================================
// Register Move Gadgets
// ============================================================================

// MOV Xd, Xn - register to register move
// Table: gadget_mov_reg[dst][src]
extern const tcti_gadget_t gadget_mov_reg[16][16];

// ============================================================================
// Data Processing - Immediate
// ============================================================================

// ADD Rd, Rn, #imm (imm = 0-15)
// Table: gadget_add_imm[dst][src][imm]
extern const tcti_gadget_t gadget_add_imm[16][16][16];

// SUB Rd, Rn, #imm (imm = 0-15)
// Table: gadget_sub_imm[dst][src][imm]
extern const tcti_gadget_t gadget_sub_imm[16][16][16];

// MOVZ Xd, #imm - load immediate from bytecode stream
// The immediate value follows this gadget in the bytecode
extern const tcti_gadget_t gadget_mov_imm[16];

// ============================================================================
// Data Processing - Register
// ============================================================================

// ADD Rd, Rn, Rm - register addition
// Table: gadget_add_reg[dst][src1][src2]
extern const tcti_gadget_t gadget_add_reg[16][16][16];

// SUB Rd, Rn, Rm - register subtraction
// Table: gadget_sub_reg[dst][src1][src2]
extern const tcti_gadget_t gadget_sub_reg[16][16][16];

// AND Rd, Rn, Rm - register AND
// Table: gadget_and_reg[dst][src1][src2]
extern const tcti_gadget_t gadget_and_reg[16][16][16];

// ORR Rd, Rn, Rm - register OR
// Table: gadget_orr_reg[dst][src1][src2]
extern const tcti_gadget_t gadget_orr_reg[16][16][16];

// EOR Rd, Rn, Rm - register XOR
// Table: gadget_eor_reg[dst][src1][src2]
extern const tcti_gadget_t gadget_eor_reg[16][16][16];

// ADDS Rd, Rn, Rm - register addition with NZCV update
// Table: gadget_adds_reg[dst][src1][src2]
extern const tcti_gadget_t gadget_adds_reg[16][16][16];

// SUBS Rd, Rn, Rm - register subtraction with NZCV update
// Table: gadget_subs_reg[dst][src1][src2]
extern const tcti_gadget_t gadget_subs_reg[16][16][16];

// CMP Xn, Xm - compare registers and update NZCV
// Table: gadget_cmp_reg[src1][src2]
extern const tcti_gadget_t gadget_cmp_reg[16][16];

// ============================================================================
// Branch Gadgets
// ============================================================================

// Unconditional branch
extern tcti_gadget_t gadget_b;

// Conditional branch (tests live NZCV flags)
// Table: gadget_bcond[cond]
extern const tcti_gadget_t gadget_bcond[16];

// Compare and branch on zero / non-zero for hot x0-x15 regs
// Tables: gadget_cbz_reg[reg], gadget_cbnz_reg[reg]
extern const tcti_gadget_t gadget_cbz_reg[16];
extern const tcti_gadget_t gadget_cbnz_reg[16];

// Branch to register (ret, br, blr)
extern tcti_gadget_t gadget_br;

// ============================================================================
// Bitfield Gadgets
// ============================================================================

// SBFM (signed bitfield move)
extern tcti_gadget_t gadget_sbfm;

// BFM (bitfield move)
extern tcti_gadget_t gadget_bfm;

// UBFM (unsigned bitfield move)
extern tcti_gadget_t gadget_ubfm;

// ============================================================================
// System Gadgets
// ============================================================================

// System call
extern tcti_gadget_t gadget_svc;

// MRS (system register read)
extern tcti_gadget_t gadget_mrs;

// MSR (system register write)
extern tcti_gadget_t gadget_msr;

// NOP
extern tcti_gadget_t gadget_nop;

// ============================================================================
// Load/Store Gadgets (with inline TLB)
// ============================================================================

// LDR Xd, [Xn, #imm] - 64-bit load
extern tcti_gadget_t gadget_ldr_x;

// STR Xd, [Xn, #imm] - 64-bit store
extern tcti_gadget_t gadget_str_x;

// ============================================================================
// Memory-Backed Register Load/Store (defined in gadgets_memory.c)
// ============================================================================
//
// Guest registers x16-x30 and SP are stored in memory (cpu_state struct).
// To operate on them, we load into temp registers (x14-x18), execute,
// then store back.

// Load guest x[16 + n] (n=0-14) into host temp register
// Table index 0 = x16, 14 = x30
extern const tcti_gadget_t gadget_load_xreg_16_to_30[15];

// Store host temp register back to guest x[16 + n]
extern const tcti_gadget_t gadget_store_xreg_16_to_30[15];

// SP load/store - uses x18 as temp
// These are naked functions, not function pointers
extern void gadget_load_sp(void);
extern void gadget_store_sp(void);

// Block exit gadget - marks end of gadget stream (defined in gadgets_memory.c)
extern tcti_gadget_t gadget_exit;

// ============================================================================
// Entry/Exit Functions
// ============================================================================

// Block entry - sets up TCTI execution environment
// Called from C with:
//   x0 = pointer to gadget array (tcti_gadget_t*)
//   x1 = pointer to cpu_state
// Loads TCTI-mapped registers and starts gadget execution
// Note: On macOS, symbols get underscore prefix
extern void tcti_entry_block(void *gadgets, struct cpu_state *cpu);
extern void _tcti_entry_block(void *gadgets, struct cpu_state *cpu);

// Block exit - saves registers and returns to C
// Called as the last gadget in a block
extern void tcti_exit_block(int reason);
extern void _tcti_exit_block(int reason);

// ============================================================================
// Diagnostic Struct for CMP-to-B.NE Handoff Debugging
// ============================================================================
struct cmp_bcond_diag {
    uint64_t magic;
    uint64_t cmp_operand_a;
    uint64_t cmp_operand_b;
    uint64_t nzcv_after_subs;
    uint64_t nzcv_saved;
    uint64_t bcond_target_pc;
    uint64_t bcond_fallthrough_pc;
    uint64_t nzcv_loaded;
    uint64_t nzcv_after_msr;
    uint64_t selected_pc;
    uint8_t  captured;
};

// External diagnostic buffer - defined in gadgets_tcti_impl.c
extern struct cmp_bcond_diag g_cmp_bcond_diag;

// Dump the CMP-to-B.NE diagnostic data (call after fault to see capture)
extern void dump_cmp_bcond_diag(void);

// Dump the STR post-index writeback diagnostic
extern void dump_str_wb_diag(void);

// Dump runtime diagnostic for pc=0xf7fa4650
extern void dump_runtime_diag(void);

// Dump emission diagnostic for pc=0xf7fa4650  
extern void dump_gen_emit_diag(void);

#ifdef __cplusplus
}
#endif

#endif /* AARCH64_TCTI_GADGETS_H */
