/*
 * TCTI Gadget Table Declarations
 * Auto-generated by tcti-gadget-gen.py
 * Version: 1.0.0
 * Date: 2026-03-21 00:00:44
 *
 * DO NOT EDIT - This file is machine generated
 */

#ifndef AARCH64_TCTI_GADGETS_H
#define AARCH64_TCTI_GADGETS_H

#include "misc.h"

#ifdef __cplusplus
extern "C" {
#endif

// Gadget function type
typedef void (*tcti_gadget_t)(void);

// Maximum gadgets per basic block
#define A64_MAX_GADGETS_PER_BLOCK 256

// Exit reason codes
#define TCTI_EXIT_NORMAL    0
#define TCTI_EXIT_SYSCALL   1
#define TCTI_EXIT_SIGNAL    2
#define TCTI_EXIT_FAULT     3

// Block exit function
extern void tcti_exit_block(int reason);

// Standard gadget epilogue - load next gadget and branch
// x28 = gadget stream pointer (increments by 8 each gadget)
// x27 = temp register, holds next gadget address
// x29 = cpu_state pointer
#define GADGET_EPILOGUE "ldr x27, [x28], #8\n\tbr x27\n\t"

// ============================================================================
// Data Processing - Register Gadgets
// ============================================================================

// ADD Rd, Rn, Rm - 16x16x16 = 4096 gadgets
extern const tcti_gadget_t gadget_add_reg[16][16][16];

// SUB Rd, Rn, Rm - 16x16x16 = 4096 gadgets
extern const tcti_gadget_t gadget_sub_reg[16][16][16];

// AND Rd, Rn, Rm - 16x16x16 = 4096 gadgets
extern const tcti_gadget_t gadget_and_reg[16][16][16];

// ORR Rd, Rn, Rm - 16x16x16 = 4096 gadgets
extern const tcti_gadget_t gadget_orr_reg[16][16][16];

// EOR Rd, Rn, Rm - 16x16x16 = 4096 gadgets
extern const tcti_gadget_t gadget_eor_reg[16][16][16];

// MOV Rd, Rn - 16x16 = 256 gadgets
extern const tcti_gadget_t gadget_mov_reg[16][16];

// ============================================================================
// Data Processing - Immediate Gadgets
// ============================================================================

// ADD Rd, Rn, #imm (simplified: small immediates 0-15)
extern const tcti_gadget_t gadget_add_imm[16][16][16];

// SUB Rd, Rn, #imm (simplified: small immediates 0-15)
extern const tcti_gadget_t gadget_sub_imm[16][16][16];

// MOVZ Rd, #imm (simplified: 0-15)
extern const tcti_gadget_t gadget_mov_imm[16];

// ============================================================================
// Branch Gadgets
// ============================================================================

// Unconditional branch
extern tcti_gadget_t gadget_b;

// Conditional branch (tests condition flags)
extern tcti_gadget_t gadget_bcond;

// Compare and branch on zero
extern tcti_gadget_t gadget_cbz;

// Compare and branch on non-zero
extern tcti_gadget_t gadget_cbnz;

// Branch to register (ret, br, blr)
extern tcti_gadget_t gadget_br;

// System Gadgets
// ============================================================================

// System call
extern tcti_gadget_t gadget_svc;

// MRS (system register read)
extern tcti_gadget_t gadget_mrs;

// MSR (system register write)
extern tcti_gadget_t gadget_msr;

// NOP
extern tcti_gadget_t gadget_nop;

// Block exit gadget - marks end of gadget stream
// This should be the last gadget in every block
extern tcti_gadget_t gadget_exit;

// ============================================================================
// Memory-Backed Register Load/Store
// ============================================================================
//
// Guest registers x16-x30 and SP are stored in memory (cpu_state struct).
// To operate on them, we load into temp registers (x14-x18), execute,
// then store back.

// Load guest x[16 + n] (n=0-14) into host temp register
// Table index 0 = x16, 14 = x30
extern const tcti_gadget_t gadget_load_xreg_16_to_30[15];

// Store host temp register back to guest x[16 + n]
extern const tcti_gadget_t gadget_store_xreg_16_to_30[15];

// SP load/store - uses x18 as temp
// These are naked functions, not function pointers
extern void gadget_load_sp(void);
extern void gadget_store_sp(void);

// ============================================================================
// Entry/Exit Functions
// ============================================================================

// Block entry - sets up TCTI execution environment
// Called from C with:
//   x0 = pointer to gadget array (tcti_gadget_t*)
//   x1 = pointer to cpu_state
// Loads TCTI-mapped registers and starts gadget execution
// Note: On macOS, symbols get underscore prefix
extern void tcti_entry_block(void *gadgets, struct cpu_state *cpu);
extern void _tcti_entry_block(void *gadgets, struct cpu_state *cpu);

// Block exit - saves registers and returns to C
// Called as the last gadget in a block
extern void tcti_exit_block(int reason);
extern void _tcti_exit_block(int reason);

#ifdef __cplusplus
}
#endif

#endif /* AARCH64_TCTI_GADGETS_H */
