#!/usr/bin/env python3
"""
TCTI Gadget Generator for aarch64

Generates pre-compiled assembly gadgets for threaded code execution.
Each gadget implements one aarch64 instruction variant.

Based on UTM's TCTI approach:
- Gadgets are naked functions with inline assembly
- Each gadget ends with epilogue that chains to next gadget
- Register mapping: x1-x16 = guest x0-x15, x28 = bytecode pointer
"""

import argparse
import os
import sys
from datetime import datetime

# Configuration
GADGET_VERSION = "1.0.0"
MAX_TCTI_REGS = 16  # x0-x15 are TCTI-mapped, x16-x30 are memory-backed

# Template for generated header file
HEADER_TEMPLATE = """/*
 * ============================================================================
 * ZERO TOLERANCE RULE: DO NOT EDIT THIS FILE
 * ============================================================================
 * 
 * This file is AUTO-GENERATED. Any manual edits are INVALID and will be
 * overwritten on the next build. DO NOT EDIT DIRECTLY.
 * 
 * Source of truth: tcti/aarch64/tcti-gadget-gen.py
 * Generator version: {version}
 * Generation date: {date}
 * Generator hash: {generator_hash}
 * 
 * If you need to change gadget behavior:
 *   1. Edit tcti/aarch64/tcti-gadget-gen.py
 *   2. Rebuild (Meson will auto-regenerate)
 *   3. Verify changes in the regenerated output
 * 
 * Generated files are disposable artifacts, not source code.
 * ============================================================================
 */

/*
 * TCTI Gadget Table Declarations
 * Auto-generated by tcti-gadget-gen.py
 */

#ifndef AARCH64_TCTI_GADGETS_H
#define AARCH64_TCTI_GADGETS_H

#include "misc.h"

#ifdef __cplusplus
extern "C" {{
#endif

struct cpu_state;

// Gadget function type
typedef void (*tcti_gadget_t)(void);

// Maximum gadgets per basic block
#define A64_MAX_GADGETS_PER_BLOCK 512

// Exit reason codes
#define TCTI_EXIT_NORMAL    0
#define TCTI_EXIT_SYSCALL   1
#define TCTI_EXIT_SIGNAL    2
#define TCTI_EXIT_FAULT     3
#define TCTI_EXIT_COMPLEX   4  // Complex instruction needs C handling (e.g., load/store)

// Block exit function
extern void tcti_exit_block(int reason);

// Standard gadget epilogue - load next gadget and branch
#define GADGET_EPILOGUE "ldr x27, [x28], #8\\n\\tbr x27\\n\\t"

// ============================================================================
// Register Move Gadgets
// ============================================================================

// MOV Xd, Xn - register to register move
// Table: gadget_mov_reg[dst][src]
extern const tcti_gadget_t gadget_mov_reg[16][16];

// ============================================================================
// Data Processing - Immediate
// ============================================================================

// ADD Rd, Rn, #imm (imm = 0-15)
// Table: gadget_add_imm[dst][src][imm]
extern const tcti_gadget_t gadget_add_imm[16][16][16];

// SUB Rd, Rn, #imm (imm = 0-15)
// Table: gadget_sub_imm[dst][src][imm]
extern const tcti_gadget_t gadget_sub_imm[16][16][16];

// MOVZ Xd, #imm - load immediate from bytecode stream
// The immediate value follows this gadget in the bytecode
extern const tcti_gadget_t gadget_mov_imm[16];

// ============================================================================
// Data Processing - Register
// ============================================================================

// ADD Rd, Rn, Rm - register addition
// Table: gadget_add_reg[dst][src1][src2]
extern const tcti_gadget_t gadget_add_reg[16][16][16];

// SUB Rd, Rn, Rm - register subtraction
// Table: gadget_sub_reg[dst][src1][src2]
extern const tcti_gadget_t gadget_sub_reg[16][16][16];

// AND Rd, Rn, Rm - register AND
// Table: gadget_and_reg[dst][src1][src2]
extern const tcti_gadget_t gadget_and_reg[16][16][16];

// ORR Rd, Rn, Rm - register OR
// Table: gadget_orr_reg[dst][src1][src2]
extern const tcti_gadget_t gadget_orr_reg[16][16][16];

// EOR Rd, Rn, Rm - register XOR
// Table: gadget_eor_reg[dst][src1][src2]
extern const tcti_gadget_t gadget_eor_reg[16][16][16];

// ADDS Rd, Rn, Rm - register addition with NZCV update
// Table: gadget_adds_reg[dst][src1][src2]
extern const tcti_gadget_t gadget_adds_reg[16][16][16];

// SUBS Rd, Rn, Rm - register subtraction with NZCV update
// Table: gadget_subs_reg[dst][src1][src2]
extern const tcti_gadget_t gadget_subs_reg[16][16][16];

// CMP Xn, Xm - compare registers and update NZCV
// Table: gadget_cmp_reg[src1][src2]
extern const tcti_gadget_t gadget_cmp_reg[16][16];

// ============================================================================
// Branch Gadgets
// ============================================================================

// Unconditional branch
extern tcti_gadget_t gadget_b;

// Conditional branch (tests live NZCV flags)
// Table: gadget_bcond[cond]
extern const tcti_gadget_t gadget_bcond[16];

// Compare and branch on zero / non-zero for hot x0-x15 regs
// Tables: gadget_cbz_reg[reg], gadget_cbnz_reg[reg]
extern const tcti_gadget_t gadget_cbz_reg[16];
extern const tcti_gadget_t gadget_cbnz_reg[16];

// Branch to register (ret, br, blr)
extern tcti_gadget_t gadget_br;

// ============================================================================
// Bitfield Gadgets
// ============================================================================

// SBFM (signed bitfield move)
extern tcti_gadget_t gadget_sbfm;

// BFM (bitfield move)
extern tcti_gadget_t gadget_bfm;

// UBFM (unsigned bitfield move)
extern tcti_gadget_t gadget_ubfm;

// ============================================================================
// System Gadgets
// ============================================================================

// System call
extern tcti_gadget_t gadget_svc;

// MRS (system register read)
extern tcti_gadget_t gadget_mrs;

// MSR (system register write)
extern tcti_gadget_t gadget_msr;

// NOP
extern tcti_gadget_t gadget_nop;

// ============================================================================
// Load/Store Gadgets (with inline TLB)
// ============================================================================

// LDR Xd, [Xn, #imm] - 64-bit load
extern tcti_gadget_t gadget_ldr_x;

// STR Xd, [Xn, #imm] - 64-bit store
extern tcti_gadget_t gadget_str_x;

// ============================================================================
// Memory-Backed Register Load/Store (defined in gadgets_memory.c)
// ============================================================================
//
// Guest registers x16-x30 and SP are stored in memory (cpu_state struct).
// To operate on them, we load into temp registers (x14-x18), execute,
// then store back.

// Load guest x[16 + n] (n=0-14) into host temp register
// Table index 0 = x16, 14 = x30
extern const tcti_gadget_t gadget_load_xreg_16_to_30[15];

// Store host temp register back to guest x[16 + n]
extern const tcti_gadget_t gadget_store_xreg_16_to_30[15];

// SP load/store - uses x18 as temp
// These are naked functions, not function pointers
extern void gadget_load_sp(void);
extern void gadget_store_sp(void);

// Block exit gadget - marks end of gadget stream (defined in gadgets_memory.c)
extern tcti_gadget_t gadget_exit;

// ============================================================================
// Entry/Exit Functions
// ============================================================================

// Block entry - sets up TCTI execution environment
// Called from C with:
//   x0 = pointer to gadget array (tcti_gadget_t*)
//   x1 = pointer to cpu_state
// Loads TCTI-mapped registers and starts gadget execution
// Note: On macOS, symbols get underscore prefix
extern void tcti_entry_block(void *gadgets, struct cpu_state *cpu);
extern void _tcti_entry_block(void *gadgets, struct cpu_state *cpu);

// Block exit - saves registers and returns to C
// Called as the last gadget in a block
extern void tcti_exit_block(int reason);
extern void _tcti_exit_block(int reason);

// ============================================================================
// Diagnostic Struct for CMP-to-B.NE Handoff Debugging
// ============================================================================
struct cmp_bcond_diag {{
    uint64_t magic;
    uint64_t cmp_operand_a;
    uint64_t cmp_operand_b;
    uint64_t nzcv_after_subs;
    uint64_t nzcv_saved;
    uint64_t bcond_target_pc;
    uint64_t bcond_fallthrough_pc;
    uint64_t nzcv_loaded;
    uint64_t nzcv_after_msr;
    uint64_t ne_eval;
    uint64_t selected_pc;
    uint8_t  captured;
}};

struct cmp_entry_diag {{
    uint64_t x29_value;
    uint64_t host_x3;
    uint64_t host_x6;
    uint8_t captured;
}};

struct cmp_entry_probe_diag {{
    uint64_t x29_value;
    uint64_t host_x3;
    uint64_t host_x6;
    uint8_t captured;
}};

// External diagnostic buffer - defined in gadgets_tcti_impl.c
extern struct cmp_bcond_diag g_cmp_bcond_diag;
extern struct cmp_entry_diag g_cmp_entry_diag;
extern struct cmp_entry_probe_diag g_cmp_entry_probe_diag;

// Dump the CMP-to-B.NE diagnostic data (call after fault to see capture)
extern void dump_cmp_bcond_diag(void);

// Dump the STR post-index writeback diagnostic
extern void dump_str_wb_diag(void);

#ifdef __cplusplus
}}
#endif

#endif /* AARCH64_TCTI_GADGETS_H */
"""

# Template for implementation file
IMPL_TEMPLATE = """/*
 * ============================================================================
 * ZERO TOLERANCE RULE: DO NOT EDIT THIS FILE
 * ============================================================================
 * 
 * This file is AUTO-GENERATED. Any manual edits are INVALID and will be
 * overwritten on the next build. DO NOT EDIT DIRECTLY.
 * 
 * Source of truth: tcti/aarch64/tcti-gadget-gen.py
 * Generator version: {version}
 * Generation date: {date}
 * Generator hash: {generator_hash}
 * 
 * If you need to change gadget behavior:
 *   1. Edit tcti/aarch64/tcti-gadget-gen.py
 *   2. Rebuild (Meson will auto-regenerate)
 *   3. Verify changes in the regenerated output
 * 
 * Generated files are disposable artifacts, not source code.
 * ============================================================================
 */

/*
 * TCTI Gadget Implementations
 * Auto-generated by tcti-gadget-gen.py
 * Regenerate with: python3 tcti/aarch64/tcti-gadget-gen.py -o <output_dir>
 */

#include "gadgets_tcti.h"
#include "emu/aarch64/cpu.h"

// ============================================================================
// Diagnostic Buffer for CMP-to-B.NE Handoff Debugging
// ============================================================================
struct cmp_bcond_diag g_cmp_bcond_diag = {{
    .magic = 0xC0FFEE01,
    .captured = 0
}};

struct cmp_entry_diag g_cmp_entry_diag = {{0}};
struct cmp_entry_probe_diag g_cmp_entry_probe_diag = {{0}};

// One-shot capture buffer for CMP x2,x5 diagnostic
struct {{
    uint64_t host_x3;
    uint64_t host_x6;
    uint64_t cpu_x2_mem;
    uint64_t cpu_x5_mem;
    uint64_t nzcv_after_subs;
    uint64_t nzcv_after_str;
    uint64_t guest_pc;
    uint8_t  captured;
}} g_cmp_capture = {{0}};

// STR post-index writeback diagnostic buffer
struct str_wb_diag {{
    uint64_t x3_before_helper;
    uint64_t x3_after_restore;
    uint64_t cpu_x2_before_call;
    uint64_t cpu_x2_after_helper;
    uint64_t captured;
}};
struct str_wb_diag g_str_wb_diag = {{0}};

// ============================================================================
// Test-Only Atomic Capture Buffers
// ============================================================================
// These are for strict unit testing only and capture state atomically
// with no conditional logic or flag-setting instructions.
struct atomic_cmp_capture {{
    uint64_t x3_before;
    uint64_t x6_before;
    uint64_t nzcv_after_subs;
}} g_atomic_cmp_capture = {{0}};

// ============================================================================
// Register Mapping
// ============================================================================
// Guest x0-x15  -> Host x1-x16 (direct mapping)
// Guest x16-x30 -> Memory backed (access via load/store gadgets)
// Guest SP (x31)-> Memory backed (access via load/store gadgets)
// Host x28      -> Bytecode pointer (gadget stream)
// Host x29      -> CPU state pointer
// Host x27      -> Next gadget pointer (temp during epilogue)

// ============================================================================
// MOV Register Gadgets
// ============================================================================

{mov_reg_gadgets}

// ============================================================================
// ADD Immediate Gadgets
// ============================================================================

{add_imm_gadgets}

// ============================================================================
// SUB Immediate Gadgets
// ============================================================================

{sub_imm_gadgets}

// ============================================================================
// MOV Immediate Gadgets (load from bytecode stream)
// ============================================================================

{mov_imm_gadgets}

// ============================================================================
// ADD Register Gadgets
// ============================================================================

{add_reg_gadgets}

// ============================================================================
// SUB Register Gadgets
// ============================================================================

{sub_reg_gadgets}

// ============================================================================
// AND Register Gadgets
// ============================================================================

{and_reg_gadgets}

// ============================================================================
// ORR Register Gadgets
// ============================================================================

{orr_reg_gadgets}

// ============================================================================
// EOR Register Gadgets
// ============================================================================

{eor_reg_gadgets}

// ============================================================================
// ADDS Register Gadgets
// ============================================================================

{adds_reg_gadgets}

// ============================================================================
// SUBS Register Gadgets
// ============================================================================

{subs_reg_gadgets}

// ============================================================================
// CMP Register Gadgets
// ============================================================================

{cmp_reg_gadgets}

// ============================================================================
// Gadget Lookup Tables
// ============================================================================

{lookup_tables}
"""


def generate_mov_reg_gadgets():
    """Generate register move gadgets (MOV Rd, Rn)."""
    gadgets = []

    for rd in range(MAX_TCTI_REGS):
        for rn in range(MAX_TCTI_REGS):
            host_rd = rd + 1
            host_rn = rn + 1

            func_name = f"gadget_mov_reg_{rd}_{rn}"

            gadget = f"""// MOV x{rd}, x{rn}
__attribute__((naked)) void {func_name}(void) {{
    asm volatile(
        "mov x{host_rd}, x{host_rn}\\n\\t"
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}}"""
            gadgets.append(gadget)

    return "\n\n".join(gadgets)


def generate_add_imm_gadgets():
    """Generate ADD immediate gadgets (ADD Rd, Rn, #imm for imm 0-15)."""
    gadgets = []

    for rd in range(MAX_TCTI_REGS):
        for rn in range(MAX_TCTI_REGS):
            for imm in range(16):
                host_rd = rd + 1
                host_rn = rn + 1

                func_name = f"gadget_add_imm_{rd}_{rn}_{imm}"

                gadget = f"""// ADD x{rd}, x{rn}, #{imm}
__attribute__((naked)) void {func_name}(void) {{
    asm volatile(
        "add x{host_rd}, x{host_rn}, #{imm}\\n\\t"
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}}"""
                gadgets.append(gadget)

    return "\n\n".join(gadgets)


def generate_sub_imm_gadgets():
    """Generate SUB immediate gadgets (SUB Rd, Rn, #imm for imm 0-15)."""
    gadgets = []

    for rd in range(MAX_TCTI_REGS):
        for rn in range(MAX_TCTI_REGS):
            for imm in range(16):
                host_rd = rd + 1
                host_rn = rn + 1

                func_name = f"gadget_sub_imm_{rd}_{rn}_{imm}"

                gadget = f"""// SUB x{rd}, x{rn}, #{imm}
__attribute__((naked)) void {func_name}(void) {{
    asm volatile(
        "sub x{host_rd}, x{host_rn}, #{imm}\\n\\t"
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}}"""
                gadgets.append(gadget)

    return "\n\n".join(gadgets)


def generate_mov_imm_gadgets():
    """Generate MOVZ immediate gadgets (load from bytecode stream)."""
    gadgets = []

    for rd in range(MAX_TCTI_REGS):
        host_rd = rd + 1

        func_name = f"gadget_mov_imm_{rd}"
        gadget = f"""// MOVZ x{rd}, #imm (load from bytecode)
__attribute__((naked)) void {func_name}(void) {{
    asm volatile(
        "ldr x{host_rd}, [x28], #8\\n\\t"
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}}"""
        gadgets.append(gadget)

    return "\n\n".join(gadgets)


def generate_add_reg_gadgets():
    """Generate ADD register gadgets (ADD Rd, Rn, Rm)."""
    gadgets = []

    for rd in range(MAX_TCTI_REGS):
        for rn in range(MAX_TCTI_REGS):
            for rm in range(MAX_TCTI_REGS):
                host_rd = rd + 1
                host_rn = rn + 1
                host_rm = rm + 1

                func_name = f"gadget_add_reg_{rd}_{rn}_{rm}"

                gadget = f"""// ADD x{rd}, x{rn}, x{rm}
__attribute__((naked)) void {func_name}(void) {{
    asm volatile(
        "add x{host_rd}, x{host_rn}, x{host_rm}\\n\\t"
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}}"""
                gadgets.append(gadget)

    return "\n\n".join(gadgets)


def generate_sub_reg_gadgets():
    """Generate SUB register gadgets (SUB Rd, Rn, Rm)."""
    gadgets = []

    for rd in range(MAX_TCTI_REGS):
        for rn in range(MAX_TCTI_REGS):
            for rm in range(MAX_TCTI_REGS):
                host_rd = rd + 1
                host_rn = rn + 1
                host_rm = rm + 1

                func_name = f"gadget_sub_reg_{rd}_{rn}_{rm}"

                gadget = f"""// SUB x{rd}, x{rn}, x{rm}
__attribute__((naked)) void {func_name}(void) {{
    asm volatile(
        "sub x{host_rd}, x{host_rn}, x{host_rm}\\n\\t"
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}}"""
                gadgets.append(gadget)

    return "\n\n".join(gadgets)


def generate_and_reg_gadgets():
    """Generate AND register gadgets (AND Rd, Rn, Rm)."""
    gadgets = []

    for rd in range(MAX_TCTI_REGS):
        for rn in range(MAX_TCTI_REGS):
            for rm in range(MAX_TCTI_REGS):
                host_rd = rd + 1
                host_rn = rn + 1
                host_rm = rm + 1

                func_name = f"gadget_and_reg_{rd}_{rn}_{rm}"

                gadget = f"""// AND x{rd}, x{rn}, x{rm}
__attribute__((naked)) void {func_name}(void) {{
    asm volatile(
        "and x{host_rd}, x{host_rn}, x{host_rm}\\n\\t"
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}}"""
                gadgets.append(gadget)

    return "\n\n".join(gadgets)


def generate_orr_reg_gadgets():
    """Generate ORR register gadgets (ORR Rd, Rn, Rm)."""
    gadgets = []

    for rd in range(MAX_TCTI_REGS):
        for rn in range(MAX_TCTI_REGS):
            for rm in range(MAX_TCTI_REGS):
                host_rd = rd + 1
                host_rn = rn + 1
                host_rm = rm + 1

                func_name = f"gadget_orr_reg_{rd}_{rn}_{rm}"

                gadget = f"""// ORR x{rd}, x{rn}, x{rm}
__attribute__((naked)) void {func_name}(void) {{
    asm volatile(
        "orr x{host_rd}, x{host_rn}, x{host_rm}\\n\\t"
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}}"""
                gadgets.append(gadget)

    return "\n\n".join(gadgets)


def generate_eor_reg_gadgets():
    """Generate EOR register gadgets (EOR Rd, Rn, Rm)."""
    gadgets = []

    for rd in range(MAX_TCTI_REGS):
        for rn in range(MAX_TCTI_REGS):
            for rm in range(MAX_TCTI_REGS):
                host_rd = rd + 1
                host_rn = rn + 1
                host_rm = rm + 1

                func_name = f"gadget_eor_reg_{rd}_{rn}_{rm}"

                gadget = f"""// EOR x{rd}, x{rn}, x{rm}
__attribute__((naked)) void {func_name}(void) {{
    asm volatile(
        "eor x{host_rd}, x{host_rn}, x{host_rm}\\n\\t"
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}}"""
                gadgets.append(gadget)

    return "\n\n".join(gadgets)


def generate_cmp_reg_gadgets():
    """Generate CMP register gadgets (CMP Xn, Xm / SUBS XZR, Xn, Xm)."""
    gadgets = []

    for rn in range(MAX_TCTI_REGS):
        for rm in range(MAX_TCTI_REGS):
            host_rn = rn + 1
            host_rm = rm + 1

            func_name = f"gadget_cmp_reg_{rn}_{rm}"

            gadget = f"""// CMP x{rn}, x{rm}
__attribute__((naked)) void {func_name}(void) {{
    asm volatile(
        "subs xzr, x{host_rn}, x{host_rm}\\n\\t"
        "mrs x17, nzcv\\n\\t"
        "str x17, [x29, #280]\\n\\t"
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}}"""
            gadgets.append(gadget)

    return "\n\n".join(gadgets)


def generate_adds_reg_gadgets():
    """Generate ADDS register gadgets (ADDS Rd, Rn, Rm)."""
    gadgets = []

    for rd in range(MAX_TCTI_REGS):
        for rn in range(MAX_TCTI_REGS):
            for rm in range(MAX_TCTI_REGS):
                host_rd = rd + 1
                host_rn = rn + 1
                host_rm = rm + 1

                func_name = f"gadget_adds_reg_{rd}_{rn}_{rm}"

                gadget = f"""// ADDS x{rd}, x{rn}, x{rm}
__attribute__((naked)) void {func_name}(void) {{
    asm volatile(
        "adds x{host_rd}, x{host_rn}, x{host_rm}\\n\\t"
        "mrs x17, nzcv\\n\\t"
        "str x17, [x29, #280]\\n\\t"
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}}"""
                gadgets.append(gadget)

    return "\n\n".join(gadgets)


def generate_subs_reg_gadgets():
    """Generate SUBS register gadgets (SUBS Rd, Rn, Rm)."""
    gadgets = []

    for rd in range(MAX_TCTI_REGS):
        for rn in range(MAX_TCTI_REGS):
            for rm in range(MAX_TCTI_REGS):
                host_rd = rd + 1
                host_rn = rn + 1
                host_rm = rm + 1

                func_name = f"gadget_subs_reg_{rd}_{rn}_{rm}"

                gadget = f"""// SUBS x{rd}, x{rn}, x{rm}
__attribute__((naked)) void {func_name}(void) {{
    asm volatile(
        "subs x{host_rd}, x{host_rn}, x{host_rm}\\n\\t"
        "mrs x17, nzcv\\n\\t"
        "str x17, [x29, #280]\\n\\t"
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}}"""
                gadgets.append(gadget)

    return "\n\n".join(gadgets)


def generate_lookup_tables():
    """Generate gadget lookup tables."""
    tables = []

    # MOV register table
    tables.append("// MOV register lookup table: gadget_mov_reg[dst][src]")
    tables.append("const tcti_gadget_t gadget_mov_reg[16][16] = {")
    for rd in range(MAX_TCTI_REGS):
        entries = [f"gadget_mov_reg_{rd}_{rn}" for rn in range(MAX_TCTI_REGS)]
        tables.append("    {" + ", ".join(entries) + "},")
    tables.append("};")
    tables.append("")

    # ADD immediate table
    tables.append("// ADD immediate lookup table: gadget_add_imm[dst][src][imm]")
    tables.append("const tcti_gadget_t gadget_add_imm[16][16][16] = {")
    for rd in range(MAX_TCTI_REGS):
        tables.append("    {")
        for rn in range(MAX_TCTI_REGS):
            entries = [f"gadget_add_imm_{rd}_{rn}_{imm}" for imm in range(16)]
            tables.append("        {" + ", ".join(entries) + "},")
        tables.append("    },")
    tables.append("};")
    tables.append("")

    # SUB immediate table
    tables.append("// SUB immediate lookup table: gadget_sub_imm[dst][src][imm]")
    tables.append("const tcti_gadget_t gadget_sub_imm[16][16][16] = {")
    for rd in range(MAX_TCTI_REGS):
        tables.append("    {")
        for rn in range(MAX_TCTI_REGS):
            entries = [f"gadget_sub_imm_{rd}_{rn}_{imm}" for imm in range(16)]
            tables.append("        {" + ", ".join(entries) + "},")
        tables.append("    },")
    tables.append("};")
    tables.append("")

    # MOV immediate table
    tables.append("// MOV immediate lookup table: gadget_mov_imm[dst]")
    entries = [f"gadget_mov_imm_{rd}" for rd in range(MAX_TCTI_REGS)]
    tables.append(
        "const tcti_gadget_t gadget_mov_imm[16] = {" + ", ".join(entries) + "};"
    )
    tables.append("")

    # ADD register table
    tables.append("// ADD register lookup table: gadget_add_reg[dst][src1][src2]")
    tables.append("const tcti_gadget_t gadget_add_reg[16][16][16] = {")
    for rd in range(MAX_TCTI_REGS):
        tables.append("    {")
        for rn in range(MAX_TCTI_REGS):
            tables.append("        {")
            for rm in range(MAX_TCTI_REGS):
                tables.append(f"            gadget_add_reg_{rd}_{rn}_{rm},")
            tables.append("        },")
        tables.append("    },")
    tables.append("};")
    tables.append("")

    # SUB register table
    tables.append("// SUB register lookup table: gadget_sub_reg[dst][src1][src2]")
    tables.append("const tcti_gadget_t gadget_sub_reg[16][16][16] = {")
    for rd in range(MAX_TCTI_REGS):
        tables.append("    {")
        for rn in range(MAX_TCTI_REGS):
            tables.append("        {")
            for rm in range(MAX_TCTI_REGS):
                tables.append(f"            gadget_sub_reg_{rd}_{rn}_{rm},")
            tables.append("        },")
        tables.append("    },")
    tables.append("};")
    tables.append("")

    # AND register table
    tables.append("// AND register lookup table: gadget_and_reg[dst][src1][src2]")
    tables.append("const tcti_gadget_t gadget_and_reg[16][16][16] = {")
    for rd in range(MAX_TCTI_REGS):
        tables.append("    {")
        for rn in range(MAX_TCTI_REGS):
            tables.append("        {")
            for rm in range(MAX_TCTI_REGS):
                tables.append(f"            gadget_and_reg_{rd}_{rn}_{rm},")
            tables.append("        },")
        tables.append("    },")
    tables.append("};")
    tables.append("")

    # ORR register table
    tables.append("// ORR register lookup table: gadget_orr_reg[dst][src1][src2]")
    tables.append("const tcti_gadget_t gadget_orr_reg[16][16][16] = {")
    for rd in range(MAX_TCTI_REGS):
        tables.append("    {")
        for rn in range(MAX_TCTI_REGS):
            tables.append("        {")
            for rm in range(MAX_TCTI_REGS):
                tables.append(f"            gadget_orr_reg_{rd}_{rn}_{rm},")
            tables.append("        },")
        tables.append("    },")
    tables.append("};")
    tables.append("")

    # EOR register table
    tables.append("// EOR register lookup table: gadget_eor_reg[dst][src1][src2]")
    tables.append("const tcti_gadget_t gadget_eor_reg[16][16][16] = {")
    for rd in range(MAX_TCTI_REGS):
        tables.append("    {")
        for rn in range(MAX_TCTI_REGS):
            tables.append("        {")
            for rm in range(MAX_TCTI_REGS):
                tables.append(f"            gadget_eor_reg_{rd}_{rn}_{rm},")
            tables.append("        },")
        tables.append("    },")
    tables.append("};")

    tables.append("")
    tables.append("// ADDS register lookup table: gadget_adds_reg[dst][src1][src2]")
    tables.append("const tcti_gadget_t gadget_adds_reg[16][16][16] = {")
    for rd in range(MAX_TCTI_REGS):
        tables.append("    {")
        for rn in range(MAX_TCTI_REGS):
            tables.append("        {")
            for rm in range(MAX_TCTI_REGS):
                tables.append(f"            gadget_adds_reg_{rd}_{rn}_{rm},")
            tables.append("        },")
        tables.append("    },")
    tables.append("};")

    tables.append("")
    tables.append("// SUBS register lookup table: gadget_subs_reg[dst][src1][src2]")
    tables.append("const tcti_gadget_t gadget_subs_reg[16][16][16] = {")
    for rd in range(MAX_TCTI_REGS):
        tables.append("    {")
        for rn in range(MAX_TCTI_REGS):
            tables.append("        {")
            for rm in range(MAX_TCTI_REGS):
                tables.append(f"            gadget_subs_reg_{rd}_{rn}_{rm},")
            tables.append("        },")
        tables.append("    },")
    tables.append("};")

    tables.append("")
    tables.append("// CMP register lookup table: gadget_cmp_reg[src1][src2]")
    tables.append("const tcti_gadget_t gadget_cmp_reg[16][16] = {")
    for rn in range(MAX_TCTI_REGS):
        entries = [f"gadget_cmp_reg_{rn}_{rm}" for rm in range(MAX_TCTI_REGS)]
        tables.append("    {" + ", ".join(entries) + "},")
    tables.append("};")

    return "\n".join(tables)


def generate_gadgets(output_dir, generator_hash="unknown"):
    """Generate all gadget files."""
    # Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)

    version = GADGET_VERSION
    date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    print(f"TCTI Gadget Generator v{version}")
    print(f"Output directory: {output_dir}")

    # Generate header file
    header_content = HEADER_TEMPLATE.format(
        version=version, date=date, generator_hash=generator_hash
    )
    header_path = os.path.join(output_dir, "gadgets_tcti.h")
    with open(header_path, "w") as f:
        f.write(header_content)
    print(f"Generated: {header_path}")

    # Generate implementation file
    print("Generating register gadgets...")
    mov_reg_gadgets = generate_mov_reg_gadgets()

    print("Generating immediate gadgets...")
    add_imm_gadgets = generate_add_imm_gadgets()
    sub_imm_gadgets = generate_sub_imm_gadgets()
    mov_imm_gadgets = generate_mov_imm_gadgets()

    print("Generating register-register gadgets...")
    add_reg_gadgets = generate_add_reg_gadgets()
    sub_reg_gadgets = generate_sub_reg_gadgets()
    and_reg_gadgets = generate_and_reg_gadgets()
    orr_reg_gadgets = generate_orr_reg_gadgets()
    eor_reg_gadgets = generate_eor_reg_gadgets()
    adds_reg_gadgets = generate_adds_reg_gadgets()
    subs_reg_gadgets = generate_subs_reg_gadgets()
    cmp_reg_gadgets = generate_cmp_reg_gadgets()

    print("Generating lookup tables...")
    lookup_tables = generate_lookup_tables()

    impl_content = IMPL_TEMPLATE.format(
        version=version,
        date=date,
        generator_hash=generator_hash,
        mov_reg_gadgets=mov_reg_gadgets,
        add_imm_gadgets=add_imm_gadgets,
        sub_imm_gadgets=sub_imm_gadgets,
        mov_imm_gadgets=mov_imm_gadgets,
        add_reg_gadgets=add_reg_gadgets,
        sub_reg_gadgets=sub_reg_gadgets,
        and_reg_gadgets=and_reg_gadgets,
        orr_reg_gadgets=orr_reg_gadgets,
        eor_reg_gadgets=eor_reg_gadgets,
        adds_reg_gadgets=adds_reg_gadgets,
        subs_reg_gadgets=subs_reg_gadgets,
        cmp_reg_gadgets=cmp_reg_gadgets,
        lookup_tables=lookup_tables,
    )

    impl_path = os.path.join(output_dir, "gadgets_tcti_impl.c")
    with open(impl_path, "w") as f:
        f.write(impl_content)
    print(f"Generated: {impl_path}")

    print("\nStatistics:")
    print(f"  TCTI-mapped registers: x0-x15 ({MAX_TCTI_REGS})")
    print(
        f"  Total gadgets: ~{16 * 16 + 16 * 16 * 16 + 16 * 16 * 16 + 16 + 16 * 16 * 16 + 16 * 16 * 16:,}"
    )
    print(f"  Memory-backed: x16-x30, SP (16)")


def compute_file_hash(filepath):
    """Compute SHA256 hash of file for validation."""
    import hashlib

    with open(filepath, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()[:16]


def main():
    parser = argparse.ArgumentParser(description="Generate TCTI gadgets for aarch64")
    parser.add_argument(
        "-o",
        "--output",
        default=".",
        help="Output directory for generated files (default: current directory)",
    )
    parser.add_argument(
        "--generator-hash",
        default=None,
        help="Path to generator file for hash computation (used by build system)",
    )
    args = parser.parse_args()

    generator_hash = "unknown"
    if args.generator_hash and os.path.exists(args.generator_hash):
        generator_hash = compute_file_hash(args.generator_hash)

    generate_gadgets(args.output, generator_hash)


if __name__ == "__main__":
    main()
