#!/usr/bin/env python3
"""
TCTI Gadget Generator for aarch64

Generates pre-compiled assembly gadgets for threaded code execution.
Each gadget implements one aarch64 instruction variant.

Based on UTM's TCTI approach:
- Gadgets are naked functions with inline assembly
- Each gadget ends with epilogue that chains to next gadget
- Register mapping: x1-x16 = guest x0-x15, x28 = bytecode pointer
"""

import argparse
import os
import sys
from datetime import datetime

# Configuration
GADGET_VERSION = "1.0.0"
MAX_TCTI_REGS = 16  # x0-x15 are TCTI-mapped, x16-x30 are memory-based

# Template for generated header file
HEADER_TEMPLATE = """/*
 * TCTI Gadget Table Declarations
 * Auto-generated by tcti-gadget-gen.py
 * Version: {version}
 * Date: {date}
 *
 * DO NOT EDIT - This file is machine generated
 */

#ifndef AARCH64_TCTI_GADGETS_H
#define AARCH64_TCTI_GADGETS_H

#include "misc.h"

#ifdef __cplusplus
extern "C" {{
#endif

// Gadget function type
typedef void (*tcti_gadget_t)(void);

// Maximum gadgets per basic block
#define A64_MAX_GADGETS_PER_BLOCK 256

// Exit reason codes
#define TCTI_EXIT_NORMAL    0
#define TCTI_EXIT_SYSCALL   1
#define TCTI_EXIT_SIGNAL    2
#define TCTI_EXIT_FAULT     3

// Block exit function
extern void tcti_exit_block(int reason);

// Standard gadget epilogue - load next gadget and branch
// x28 = gadget stream pointer (increments by 8 each gadget)
// x27 = temp register, holds next gadget address
// x29 = cpu_state pointer
#define GADGET_EPILOGUE "ldr x27, [x28], #8\\n\\tbr x27\\n\\t"

// ============================================================================
// Data Processing - Register Gadgets
// ============================================================================

// ADD Rd, Rn, Rm - 16x16x16 = 4096 gadgets
extern const tcti_gadget_t gadget_add_reg[{max_regs}][{max_regs}][{max_regs}];

// SUB Rd, Rn, Rm - 16x16x16 = 4096 gadgets
extern const tcti_gadget_t gadget_sub_reg[{max_regs}][{max_regs}][{max_regs}];

// AND Rd, Rn, Rm - 16x16x16 = 4096 gadgets
extern const tcti_gadget_t gadget_and_reg[{max_regs}][{max_regs}][{max_regs}];

// ORR Rd, Rn, Rm - 16x16x16 = 4096 gadgets
extern const tcti_gadget_t gadget_orr_reg[{max_regs}][{max_regs}][{max_regs}];

// EOR Rd, Rn, Rm - 16x16x16 = 4096 gadgets
extern const tcti_gadget_t gadget_eor_reg[{max_regs}][{max_regs}][{max_regs}];

// MOV Rd, Rn - 16x16 = 256 gadgets
extern const tcti_gadget_t gadget_mov_reg[{max_regs}][{max_regs}];

// ============================================================================
// Data Processing - Immediate Gadgets
// ============================================================================

// ADD Rd, Rn, #imm (simplified: small immediates 0-15)
extern const tcti_gadget_t gadget_add_imm[{max_regs}][{max_regs}][16];

// SUB Rd, Rn, #imm (simplified: small immediates 0-15)
extern const tcti_gadget_t gadget_sub_imm[{max_regs}][{max_regs}][16];

// MOVZ Rd, #imm (simplified: 0-15)
extern const tcti_gadget_t gadget_mov_imm[{max_regs}];

// ============================================================================
// Branch Gadgets
// ============================================================================

// Unconditional branch
extern tcti_gadget_t gadget_b;

// Conditional branch (tests condition flags)
extern tcti_gadget_t gadget_bcond;

// Compare and branch on zero
extern tcti_gadget_t gadget_cbz;

// Compare and branch on non-zero
extern tcti_gadget_t gadget_cbnz;

// Branch to register (ret, br, blr)
extern tcti_gadget_t gadget_br;

// ============================================================================
// System Gadgets
// ============================================================================

// System call
extern tcti_gadget_t gadget_svc;

// MRS (system register read)
extern tcti_gadget_t gadget_mrs;

// MSR (system register write)
extern tcti_gadget_t gadget_msr;

// NOP
extern tcti_gadget_t gadget_nop;

#ifdef __cplusplus
}}
#endif

#endif /* AARCH64_TCTI_GADGETS_H */
"""

# Template for implementation file
IMPL_TEMPLATE = """/*
 * TCTI Gadget Implementations
 * Auto-generated by tcti-gadget-gen.py
 * Version: {version}
 * Date: {date}
 *
 * DO NOT EDIT - This file is machine generated
 */

#include "tcti/aarch64/gadgets_tcti.h"
#include "emu/aarch64/cpu.h"

// ============================================================================
// Register Mapping
// ============================================================================
// Guest x0-x15  -> Host x1-x16 (direct mapping)
// Guest x16-x30 -> Memory (cpu->x[16-30])
// Guest SP      -> Host x17 (scratch) + memory
// Bytecode ptr  -> Host x28
// CPU state ptr -> Host x29
// Temp/Link     -> Host x27, x30
//
// GADGET_EPILOGUE:
//   ldr x27, [x28], #8    // Load next gadget address, advance bytecode
//   br x27                // Jump to next gadget
// ============================================================================

#define CPU_STATE x29

// Helper to access memory-backed registers
#define LOAD_XREG(n) "ldr x0, [x29, #(offsetof(struct cpu_state, x) + (n)*8)]\\n\\t"
#define STORE_XREG(n) "str x0, [x29, #(offsetof(struct cpu_state, x) + (n)*8)]\\n\\t"

// ============================================================================
// Data Processing - Register Gadgets
// ============================================================================

{dp_reg_gadgets}

// ============================================================================
// Data Processing - Immediate Gadgets
// ============================================================================

{dp_imm_gadgets}

// ============================================================================
// Branch Gadgets
// ============================================================================

{branch_gadgets}

// ============================================================================
// System Gadgets
// ============================================================================

{system_gadgets}

// ============================================================================
// Gadget Lookup Tables
// ============================================================================

{gadget_tables}
"""


def generate_add_reg_gadgets():
    """Generate ADD register gadgets and collect prototypes."""
    gadgets = []
    prototypes = []

    for rd in range(MAX_TCTI_REGS):
        for rn in range(MAX_TCTI_REGS):
            for rm in range(MAX_TCTI_REGS):
                host_rd = rd + 1
                host_rn = rn + 1
                host_rm = rm + 1

                func_name = f"gadget_add_reg_{rd}_{rn}_{rm}"
                prototypes.append(f"void {func_name}(void);")

                gadget = f"""// ADD x{rd}, x{rn}, x{rm}
__attribute__((naked)) void {func_name}(void) {{
    asm volatile(
        "add x{host_rd}, x{host_rn}, x{host_rm}\\n\\t"
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}}"""
                gadgets.append(gadget)

    return "\n\n".join(gadgets), prototypes


def generate_sub_reg_gadgets():
    """Generate SUB register gadgets."""
    gadgets = []

    for rd in range(MAX_TCTI_REGS):
        for rn in range(MAX_TCTI_REGS):
            for rm in range(MAX_TCTI_REGS):
                host_rd = rd + 1
                host_rn = rn + 1
                host_rm = rm + 1

                func_name = f"gadget_sub_reg_{rd}_{rn}_{rm}"

                gadget = f"""// SUB x{rd}, x{rn}, x{rm}
__attribute__((naked)) void {func_name}(void) {{
    asm volatile(
        "sub x{host_rd}, x{host_rn}, x{host_rm}\\n\\t"
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}}"""
                gadgets.append(gadget)

    return "\n\n".join(gadgets)


def generate_logical_reg_gadgets():
    """Generate AND, ORR, EOR gadgets."""
    gadgets = []
    ops = [
        ("and", "gadget_and_reg"),
        ("orr", "gadget_orr_reg"),
        ("eor", "gadget_eor_reg"),
    ]

    for op, prefix in ops:
        for rd in range(MAX_TCTI_REGS):
            for rn in range(MAX_TCTI_REGS):
                for rm in range(MAX_TCTI_REGS):
                    host_rd = rd + 1
                    host_rn = rn + 1
                    host_rm = rm + 1

                    func_name = f"{prefix}_{rd}_{rn}_{rm}"

                    gadget = f"""// {op.upper()} x{rd}, x{rn}, x{rm}
__attribute__((naked)) void {func_name}(void) {{
    asm volatile(
        "{op} x{host_rd}, x{host_rn}, x{host_rm}\\n\\t"
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}}"""
                    gadgets.append(gadget)

    return "\n\n".join(gadgets)


def generate_mov_reg_gadgets():
    """Generate MOV register gadgets."""
    gadgets = []

    for rd in range(MAX_TCTI_REGS):
        for rn in range(MAX_TCTI_REGS):
            host_rd = rd + 1
            host_rn = rn + 1

            func_name = f"gadget_mov_reg_{rd}_{rn}"

            gadget = f"""// MOV x{rd}, x{rn}
__attribute__((naked)) void {func_name}(void) {{
    asm volatile(
        "mov x{host_rd}, x{host_rn}\\n\\t"
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}}"""
            gadgets.append(gadget)

    return "\n\n".join(gadgets)


def generate_add_imm_gadgets():
    """Generate ADD immediate gadgets (ADD Rd, Rn, #imm for imm 0-15)."""
    gadgets = []

    # ADD with small immediates 0-15
    for rd in range(MAX_TCTI_REGS):
        for rn in range(MAX_TCTI_REGS):
            for imm in range(16):  # 0-15
                host_rd = rd + 1
                host_rn = rn + 1

                func_name = f"gadget_add_imm_{rd}_{rn}_{imm}"

                gadget = f"""// ADD x{rd}, x{rn}, #{imm}
__attribute__((naked)) void {func_name}(void) {{
    asm volatile(
        "add x{host_rd}, x{host_rn}, #{imm}\\n\\t"
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}}"""
                gadgets.append(gadget)

    return "\n\n".join(gadgets)


def generate_sub_imm_gadgets():
    """Generate SUB immediate gadgets (SUB Rd, Rn, #imm for imm 0-15)."""
    gadgets = []

    # SUB with small immediates 0-15
    for rd in range(MAX_TCTI_REGS):
        for rn in range(MAX_TCTI_REGS):
            for imm in range(16):  # 0-15
                host_rd = rd + 1
                host_rn = rn + 1

                func_name = f"gadget_sub_imm_{rd}_{rn}_{imm}"

                gadget = f"""// SUB x{rd}, x{rn}, #{imm}
__attribute__((naked)) void {func_name}(void) {{
    asm volatile(
        "sub x{host_rd}, x{host_rn}, #{imm}\\n\\t"
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}}"""
                gadgets.append(gadget)

    return "\n\n".join(gadgets)


def generate_dp_imm_gadgets():
    """Generate immediate data processing gadgets."""
    gadgets = []

    # MOVZ with immediate 0-255 (simplified)
    for rd in range(MAX_TCTI_REGS):
        host_rd = rd + 1

        # MOVZ x{rd}, #0 (clear register)
        func_name = f"gadget_mov_imm_{rd}"
        gadget = f"""// MOVZ x{rd}, #imm (via mov)
__attribute__((naked)) void {func_name}(void) {{
    // For immediates, we'd need to load from bytecode stream
    // This is a placeholder - real implementation loads immediate
    asm volatile(
        "mov x{host_rd}, #0\\n\\t"  // Simplified - should load from bytecode
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}}"""
        gadgets.append(gadget)

    return "\n\n".join(gadgets)


def generate_branch_gadgets():
    """Generate branch gadgets."""
    gadgets = []

    # Unconditional branch
    gadgets.append("""// B (unconditional branch)
__attribute__((naked)) void gadget_b_impl(void) {
    asm volatile(
        "ldr x0, [x28], #8\\n\\t"     // Load target PC from bytecode
        "str x0, [x29, %[pc_off]]\\n\\t"  // Store to cpu->pc
        "mov x27, #1\\n\\t"            // Signal block exit
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
        :
        : [pc_off] "i" (offsetof(struct cpu_state, pc))
    );
}""")

    # Conditional branch
    gadgets.append("""// B.cond (conditional branch)
__attribute__((naked)) void gadget_bcond_impl(void) {
    asm volatile(
        "ldr x0, [x28], #8\\n\\t"     // Load condition and target
        "ldr x1, [x29, %[pstate_off]]\\n\\t"  // Load PSTATE
        // Test condition...
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
        :
        : [pstate_off] "i" (offsetof(struct cpu_state, pstate))
    );
}""")

    # Branch register (RET, BR, BLR)
    gadgets.append("""// BR/RET (branch to register)
__attribute__((naked)) void gadget_br_impl(void) {
    asm volatile(
        "mov x27, #1\\n\\t"            // Signal block exit
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}""")

    # CBZ/CBNZ
    gadgets.append("""// CBZ (compare and branch on zero)
__attribute__((naked)) void gadget_cbz_impl(void) {
    asm volatile(
        "ldr x0, [x28], #8\\n\\t"     // Load register number and target
        // Test if register is zero...
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}""")

    return "\n\n".join(gadgets)


def generate_system_gadgets():
    """Generate system instruction gadgets."""
    gadgets = []

    # SVC (syscall)
    gadgets.append("""// SVC (system call)
__attribute__((naked)) void gadget_svc_impl(void) {
    asm volatile(
        "mov x27, #2\\n\\t"            // Signal syscall exit
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}""")

    # NOP
    gadgets.append("""// NOP
__attribute__((naked)) void gadget_nop_impl(void) {
    asm volatile(
        "nop\\n\\t"
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}""")

    # MRS (system register read)
    gadgets.append("""// MRS (system register read)
__attribute__((naked)) void gadget_mrs_impl(void) {
    asm volatile(
        "ldr x0, [x28], #8\\n\\t"     // Load system register number
        // Read system register to x0...
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}""")

    # MSR (system register write)
    gadgets.append("""// MSR (system register write)
__attribute__((naked)) void gadget_msr_impl(void) {
    asm volatile(
        "ldr x0, [x28], #8\\n\\t"     // Load system register number
        // Write x0 to system register...
        "ldr x27, [x28], #8\\n\\t"
        "br x27\\n\\t"
    );
}""")

    return "\n\n".join(gadgets)


def generate_gadget_tables():
    """Generate the lookup tables for all gadgets."""
    tables = []

    # ADD table
    tables.append(f"// ADD register table")
    tables.append(
        f"const tcti_gadget_t gadget_add_reg[{MAX_TCTI_REGS}][{MAX_TCTI_REGS}][{MAX_TCTI_REGS}] = {{"
    )
    for rd in range(MAX_TCTI_REGS):
        tables.append(f"    [{rd}] = {{")
        for rn in range(MAX_TCTI_REGS):
            entries = [f"gadget_add_reg_{rd}_{rn}_{rm}" for rm in range(MAX_TCTI_REGS)]
            tables.append(f"        [{rn}] = {{{', '.join(entries)}}},")
        tables.append("    },")
    tables.append("};\n")

    # SUB table
    tables.append(f"// SUB register table")
    tables.append(
        f"const tcti_gadget_t gadget_sub_reg[{MAX_TCTI_REGS}][{MAX_TCTI_REGS}][{MAX_TCTI_REGS}] = {{"
    )
    for rd in range(MAX_TCTI_REGS):
        tables.append(f"    [{rd}] = {{")
        for rn in range(MAX_TCTI_REGS):
            entries = [f"gadget_sub_reg_{rd}_{rn}_{rm}" for rm in range(MAX_TCTI_REGS)]
            tables.append(f"        [{rn}] = {{{', '.join(entries)}}},")
        tables.append("    },")
    tables.append("};\n")

    # And table
    tables.append(f"// AND register table")
    tables.append(
        f"const tcti_gadget_t gadget_and_reg[{MAX_TCTI_REGS}][{MAX_TCTI_REGS}][{MAX_TCTI_REGS}] = {{"
    )
    for rd in range(MAX_TCTI_REGS):
        tables.append(f"    [{rd}] = {{")
        for rn in range(MAX_TCTI_REGS):
            entries = [f"gadget_and_reg_{rd}_{rn}_{rm}" for rm in range(MAX_TCTI_REGS)]
            tables.append(f"        [{rn}] = {{{', '.join(entries)}}},")
        tables.append("    },")
    tables.append("};\n")

    # ORR table
    tables.append(f"// ORR register table")
    tables.append(
        f"const tcti_gadget_t gadget_orr_reg[{MAX_TCTI_REGS}][{MAX_TCTI_REGS}][{MAX_TCTI_REGS}] = {{"
    )
    for rd in range(MAX_TCTI_REGS):
        tables.append(f"    [{rd}] = {{")
        for rn in range(MAX_TCTI_REGS):
            entries = [f"gadget_orr_reg_{rd}_{rn}_{rm}" for rm in range(MAX_TCTI_REGS)]
            tables.append(f"        [{rn}] = {{{', '.join(entries)}}},")
        tables.append("    },")
    tables.append("};\n")

    # EOR table
    tables.append(f"// EOR register table")
    tables.append(
        f"const tcti_gadget_t gadget_eor_reg[{MAX_TCTI_REGS}][{MAX_TCTI_REGS}][{MAX_TCTI_REGS}] = {{"
    )
    for rd in range(MAX_TCTI_REGS):
        tables.append(f"    [{rd}] = {{")
        for rn in range(MAX_TCTI_REGS):
            entries = [f"gadget_eor_reg_{rd}_{rn}_{rm}" for rm in range(MAX_TCTI_REGS)]
            tables.append(f"        [{rn}] = {{{', '.join(entries)}}},")
        tables.append("    },")
    tables.append("};\n")

    # MOV table
    tables.append(f"// MOV register table")
    tables.append(
        f"const tcti_gadget_t gadget_mov_reg[{MAX_TCTI_REGS}][{MAX_TCTI_REGS}] = {{"
    )
    for rd in range(MAX_TCTI_REGS):
        entries = [f"gadget_mov_reg_{rd}_{rn}" for rn in range(MAX_TCTI_REGS)]
        tables.append(f"    [{rd}] = {{{', '.join(entries)}}},")
    tables.append("};\n")

    # ADD immediate table (16x16x16 for Rd, Rn, imm)
    tables.append(f"// ADD immediate table")
    tables.append(
        f"const tcti_gadget_t gadget_add_imm[{MAX_TCTI_REGS}][{MAX_TCTI_REGS}][16] = {{"
    )
    for rd in range(MAX_TCTI_REGS):
        tables.append(f"    [{rd}] = {{")
        for rn in range(MAX_TCTI_REGS):
            entries = [f"gadget_add_imm_{rd}_{rn}_{imm}" for imm in range(16)]
            tables.append(f"        [{rn}] = {{{', '.join(entries)}}},")
        tables.append("    },")
    tables.append("};\n")

    # SUB immediate table (16x16x16 for Rd, Rn, imm)
    tables.append(f"// SUB immediate table")
    tables.append(
        f"const tcti_gadget_t gadget_sub_imm[{MAX_TCTI_REGS}][{MAX_TCTI_REGS}][16] = {{"
    )
    for rd in range(MAX_TCTI_REGS):
        tables.append(f"    [{rd}] = {{")
        for rn in range(MAX_TCTI_REGS):
            entries = [f"gadget_sub_imm_{rd}_{rn}_{imm}" for imm in range(16)]
            tables.append(f"        [{rn}] = {{{', '.join(entries)}}},")
        tables.append("    },")
    tables.append("};\n")

    # MOV immediate table (simplified)
    tables.append(f"// MOV immediate table")
    entries = [f"gadget_mov_imm_{rd}" for rd in range(MAX_TCTI_REGS)]
    tables.append(
        f"const tcti_gadget_t gadget_mov_imm[{MAX_TCTI_REGS}] = {{{', '.join(entries)}}};\n"
    )

    # Branch gadgets (singletons)
    tables.append("// Branch gadgets")
    tables.append("tcti_gadget_t gadget_b = gadget_b_impl;")
    tables.append("tcti_gadget_t gadget_bcond = gadget_bcond_impl;")
    tables.append("tcti_gadget_t gadget_cbz = gadget_cbz_impl;")
    tables.append("tcti_gadget_t gadget_cbnz = gadget_cbz_impl;")  # Same implementation
    tables.append("tcti_gadget_t gadget_br = gadget_br_impl;")
    tables.append("")
    tables.append("// System gadgets")
    tables.append("tcti_gadget_t gadget_svc = gadget_svc_impl;")
    tables.append("tcti_gadget_t gadget_mrs = gadget_mrs_impl;")
    tables.append("tcti_gadget_t gadget_msr = gadget_msr_impl;")
    tables.append("tcti_gadget_t gadget_nop = gadget_nop_impl;")

    return "\n".join(tables)


def main():
    parser = argparse.ArgumentParser(description="Generate TCTI gadgets for aarch64")
    parser.add_argument("-o", "--output", default=".", help="Output directory")
    parser.add_argument(
        "--header-only", action="store_true", help="Generate only header file"
    )
    parser.add_argument(
        "--impl-only", action="store_true", help="Generate only implementation file"
    )
    args = parser.parse_args()

    print(f"TCTI Gadget Generator v{GADGET_VERSION}")
    print(f"Output directory: {args.output}")

    date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Generate header file
    if not args.impl_only:
        header_path = os.path.join(args.output, "gadgets_tcti.h")
        header_content = HEADER_TEMPLATE.format(
            version=GADGET_VERSION, date=date, max_regs=MAX_TCTI_REGS
        )
        with open(header_path, "w") as f:
            f.write(header_content)
        print(f"Generated: {header_path}")

    # Generate implementation file
    if not args.header_only:
        impl_path = os.path.join(args.output, "gadgets_tcti_impl.c")

        print("Generating register gadgets...")
        add_gadgets = generate_add_reg_gadgets()[0]
        sub_gadgets = generate_sub_reg_gadgets()
        logical_gadgets = generate_logical_reg_gadgets()
        mov_reg_gadgets = generate_mov_reg_gadgets()

        print("Generating immediate gadgets...")
        add_imm_gadgets = generate_add_imm_gadgets()
        sub_imm_gadgets = generate_sub_imm_gadgets()
        imm_gadgets = generate_dp_imm_gadgets()

        print("Generating branch gadgets...")
        branch_gadgets = generate_branch_gadgets()

        print("Generating system gadgets...")
        system_gadgets = generate_system_gadgets()

        print("Generating lookup tables...")
        tables = generate_gadget_tables()

        impl_content = IMPL_TEMPLATE.format(
            version=GADGET_VERSION,
            date=date,
            dp_reg_gadgets="\n".join(
                [add_gadgets, sub_gadgets, logical_gadgets, mov_reg_gadgets]
            ),
            dp_imm_gadgets="\n".join([add_imm_gadgets, sub_imm_gadgets, imm_gadgets]),
            branch_gadgets=branch_gadgets,
            system_gadgets=system_gadgets,
            gadget_tables=tables,
        )

        with open(impl_path, "w") as f:
            f.write(impl_content)
        print(f"Generated: {impl_path}")

    # Statistics
    total_gadgets = (
        5 * MAX_TCTI_REGS**3  # ADD, SUB, AND, ORR, EOR reg (5 * 4096)
        + 2 * MAX_TCTI_REGS**2 * 16  # ADD imm, SUB imm (2 * 256 * 16)
        + MAX_TCTI_REGS**2  # MOV reg (256)
        + MAX_TCTI_REGS  # MOV imm (16)
        + 8  # Branch/system (8)
    )
    print(f"\nStatistics:")
    print(f"  TCTI-mapped registers: x0-x{MAX_TCTI_REGS - 1} ({MAX_TCTI_REGS})")
    print(f"  Total gadgets: ~{total_gadgets:,}")
    print(f"  Memory-backed: x{MAX_TCTI_REGS}-x30, SP (16)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
